import mock
import os
import pandas as pd
import pytest
from datetime import datetime
from flexmock import flexmock
from sports import utils
from sports.nba.roster import Player, Roster
from sports.nba.teams import Team
from ..utils import read_file


YEAR = 2022


def mock_pyquery(url):

    if 'DEN' in url:
        return read_file('DEN-2022.html', 'nba', 'roster')
    if 'bartowi01' in url:
        return read_file('bartowi01.html', 'nba', 'roster')
    if 'bolbo01' in url:
        return read_file('bolbo01.html', 'nba', 'roster')
    if 'jokicni01' in url:
        return read_file('jokicni01.html', 'nba', 'roster')
    if 'BAD' in url:
        return None
    return None


def mock_request(url):
    class MockRequest:
        def __init__(self, html_contents, status_code=200):
            self.status_code = status_code
            self.html_contents = html_contents
            self.text = html_contents

    if str(YEAR) in url:
        return MockRequest('good')
    else:
        return MockRequest('bad', status_code=404)


class TestNBAPlayer:
    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def setup_method(self, *args, **kwargs):
        self.results_career = {
            'and_ones': 280,
            'assist_percentage': 34.2,
            'assists': 3397,
            'assists_per_poss': 10.2,
            'block_percentage': 2.0,
            'blocking_fouls': None,
            'blocks': 384,
            'blocks_per_poss': 1.2,
            'box_plus_minus': 8.9,
            'center_percentage': 99,
            'defensive_box_plus_minus': 2.5,
            'defensive_rebound_percentage': 28.1,
            'defensive_rebounds': 4166,
            'defensive_rebounds_per_poss': 12.5,
            'defensive_win_shares': 23.0,
            'dunks': 150,
            'effective_field_goal_percentage': 0.58,
            'field_goal_attempts': 7515,
            'field_goal_attempts_per_poss': 22.6,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.463,
            'field_goal_perc_ten_to_sixteen_feet': 0.498,
            'field_goal_perc_three_to_ten_feet': 0.562,
            'field_goal_perc_zero_to_three_feet': 0.708,
            'field_goal_percentage': 0.544,
            'field_goals': 4085,
            'field_goals_per_poss': 12.3,
            'free_throw_attempt_rate': 0.307,
            'free_throw_attempts': 2310,
            'free_throw_attempts_per_poss': 6.9,
            'free_throw_percentage': 0.831,
            'free_throws': 1920,
            'free_throws_per_poss': 5.8,
            'games_played': 540,
            'games_started': 499,
            'half_court_heaves': 18,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 388,
            'minutes_played': 16422,
            'nationality': 'Serbia',
            'net_plus_minus': 9.4,
            'offensive_box_plus_minus': 6.5,
            'offensive_fouls': 164,
            'offensive_rebound_percentage': 9.6,
            'offensive_rebounds': 1413,
            'offensive_rebounds_per_poss': 4.2,
            'offensive_win_shares': 59.0,
            'on_court_plus_minus': 5.7,
            'other_turnovers': None,
            'passing_turnovers': 822,
            'percentage_field_goals_as_dunks': 0.021,
            'percentage_of_three_pointers_from_corner': 0.05,
            'percentage_shots_three_pointers': 0.21,
            'percentage_shots_two_pointers': 0.79,
            'percentage_sixteen_foot_plus_two_pointers': 0.079,
            'percentage_ten_to_sixteen_footers': 0.107,
            'percentage_three_to_ten_footers': 0.317,
            'percentage_zero_to_three_footers': 0.283,
            'personal_fouls': 1502,
            'personal_fouls_per_poss': 4.5,
            'player_efficiency_rating': 27.2,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 10634,
            'points_per_poss': 31.9,
            'points_generated_by_assists': 7861,
            'position': 'C',
            'power_forward_percentage': 1,
            'salary': 115361091.0,
            'shooting_distance': 9.9,
            'shooting_fouls': 671,
            'shooting_fouls_drawn': 899,
            'shooting_guard_percentage': 0,
            'shots_blocked': 383,
            'small_forward_percentage': 0,
            'steal_percentage': 1.9,
            'steals': 646,
            'steals_per_poss': 1.9,
            'take_fouls': None,
            'team_abbreviation': '',
            'three_point_attempt_rate': 0.21,
            'three_point_attempts': 1581,
            'three_point_attempts_per_poss': 4.7,
            'three_point_percentage': 0.344,
            'three_point_shot_percentage_from_corner': 0.38,
            'three_pointers': 544,
            'three_pointers_assisted_percentage': 0.91,
            'three_pointers_per_poss': 1.6,
            'total_rebound_percentage': 18.9,
            'total_rebounds': 5579,
            'total_rebounds_per_poss': 16.8,
            'true_shooting_percentage': 0.623,
            'turnover_percentage': 15.0,
            'turnovers': 1503,
            'turnovers_per_poss': 4.5,
            'two_point_attempts': 5934,
            'two_point_attempts_per_poss': 17.8,
            'two_point_percentage': 0.597,
            'two_pointers': 3541,
            'two_pointers_per_poss': 10.6,
            'two_pointers_assisted_percentage': 0.532,
            'usage_percentage': 26.5,
            'value_over_replacement_player': 45.3,
            'weight': 284,
            'win_shares': 82.0,
            'win_shares_per_48_minutes': 0.24,
            'contract': {
                '2022-23': '$33,047,803',
                '2023-24': '$46,550,000',
                '2024-25': '$50,274,000',
                '2025-26': '$53,998,000',
                '2026-27': '$57,722,000',
                '2027-28': '$61,446,000'
            }
        }

        self.results_2022 = {
            'and_ones': 72,
            'assist_percentage': 42.6,
            'assists': 584,
            'assists_per_poss': 11.6,
            'block_percentage': 2.3,
            'blocking_fouls': None,
            'blocks': 63,
            'blocks_per_poss': 1.2,
            'box_plus_minus': 13.7,
            'center_percentage': 100,
            'defensive_box_plus_minus': 4.5,
            'defensive_rebound_percentage': 35.5,
            'defensive_rebounds': 813,
            'defensive_rebounds_per_poss': 16.1,
            'defensive_win_shares': 4.5,
            'dunks': 31,
            'effective_field_goal_percentage': 0.62,
            'field_goal_attempts': 1311,
            'field_goal_attempts_per_poss': 26.0,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.467,
            'field_goal_perc_ten_to_sixteen_feet': 0.565,
            'field_goal_perc_three_to_ten_feet': 0.606,
            'field_goal_perc_zero_to_three_feet': 0.776,
            'field_goal_percentage': 0.583,
            'field_goals': 764,
            'field_goals_per_poss': 15.1,
            'free_throw_attempt_rate': 0.357,
            'free_throw_attempts': 468,
            'free_throw_attempts_per_poss': 9.3,
            'free_throw_percentage': 0.81,
            'free_throws': 379,
            'free_throws_per_poss': 7.5,
            'games_played': 74,
            'games_started': 74,
            'half_court_heaves': 3,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 76,
            'minutes_played': 2476,
            'nationality': 'Serbia',
            'net_plus_minus': 16.4,
            'offensive_box_plus_minus': 9.2,
            'offensive_fouls': 21,
            'offensive_rebound_percentage': 9.6,
            'offensive_rebounds': 206,
            'offensive_rebounds_per_poss': 4.1,
            'offensive_win_shares': 10.8,
            'on_court_plus_minus': 8.4,
            'other_turnovers': None,
            'passing_turnovers': 173,
            'percentage_field_goals_as_dunks': 0.025,
            'percentage_of_three_pointers_from_corner': 0.038,
            'percentage_shots_three_pointers': 0.22,
            'percentage_shots_two_pointers': 0.78,
            'percentage_sixteen_foot_plus_two_pointers': 0.046,
            'percentage_ten_to_sixteen_footers': 0.082,
            'percentage_three_to_ten_footers': 0.384,
            'percentage_zero_to_three_footers': 0.268,
            'personal_fouls': 191,
            'personal_fouls_per_poss': 3.8,
            'player_efficiency_rating': 32.8,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 2004,
            'points_per_poss': 39.7,
            'points_generated_by_assists': 1356,
            'position': 'C',
            'power_forward_percentage': 0,
            'salary': 30510423.0,
            'shooting_distance': 10.2,
            'shooting_fouls': 101,
            'shooting_fouls_drawn': 188,
            'shooting_guard_percentage': 0,
            'shots_blocked': 66,
            'small_forward_percentage': 0,
            'steal_percentage': 2.2,
            'steals': 109,
            'steals_per_poss': 2.2,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.22,
            'three_point_attempts': 288,
            'three_point_attempts_per_poss': 5.7,
            'three_point_percentage': 0.337,
            'three_point_shot_percentage_from_corner': 0.273,
            'three_pointers': 97,
            'three_pointers_assisted_percentage': 0.918,
            'three_pointers_per_poss': 1.9,
            'total_rebound_percentage': 23.0,
            'total_rebounds': 1019,
            'total_rebounds_per_poss': 20.2,
            'true_shooting_percentage': 0.661,
            'turnover_percentage': 15.6,
            'turnovers': 281,
            'turnovers_per_poss': 5.6,
            'two_point_attempts': 1023,
            'two_point_attempts_per_poss': 20.3,
            'two_point_percentage': 0.652,
            'two_pointers': 667,
            'two_pointers_per_poss': 13.2,
            'two_pointers_assisted_percentage': 0.58,
            'usage_percentage': 31.9,
            'value_over_replacement_player': 9.8,
            'weight': 284,
            'win_shares': 15.2,
            'win_shares_per_48_minutes': 0.296
        }

        self.player = Player('jokicni01')

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_nba_player_returns_requested_player_career_stats(self, *args, **kwargs):
        # Request the career stats
        player = self.player('')

        for attribute, value in self.results_career.items():
            assert getattr(player, attribute) == value

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_nba_player_returns_requested_player_season_stats(self, *args, **kwargs):
        # Request the 2017-18 stats
        player = self.player('2021-22')

        for attribute, value in self.results_2022.items():
            assert getattr(player, attribute) == value

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_dataframe_returns_dataframe(self, *args, **kwargs):
        dataframe = [
            {'and_ones': 24,
            'assist_percentage': 18.1,
            'assists': 189,
            'assists_per_poss': 5.5,
            'block_percentage': 2.3,
            'blocking_fouls': None,
            'blocks': 50,
            'blocks_per_poss': 1.4,
            'box_plus_minus': 3.9,
            'center_percentage': 95,
            'defensive_box_plus_minus': 1.3,
            'defensive_rebound_percentage': 24.7,
            'defensive_rebounds': 379,
            'defensive_rebounds_per_poss': 11.0,
            'defensive_win_shares': 2.2,
            'dunks': 11,
            'effective_field_goal_percentage': 0.535,
            'field_goal_attempts': 600,
            'field_goal_attempts_per_poss': 17.4,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.415,
            'field_goal_perc_ten_to_sixteen_feet': 0.447,
            'field_goal_perc_three_to_ten_feet': 0.477,
            'field_goal_perc_zero_to_three_feet': 0.622,
            'field_goal_percentage': 0.512,
            'field_goals': 307,
            'field_goals_per_poss': 8.9,
            'free_throw_attempt_rate': 0.317,
            'free_throw_attempts': 190,
            'free_throw_attempts_per_poss': 5.5,
            'free_throw_percentage': 0.811,
            'free_throws': 154,
            'free_throws_per_poss': 4.5,
            'games_played': 80,
            'games_started': 55,
            'half_court_heaves': 0,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 28,
            'minutes_played': 1733,
            'nationality': 'Serbia',
            'net_plus_minus': 9.5,
            'offensive_box_plus_minus': 2.6,
            'offensive_fouls': 15,
            'offensive_rebound_percentage': 11.4,
            'offensive_rebounds': 181,
            'offensive_rebounds_per_poss': 5.2,
            'offensive_win_shares': 4.5,
            'on_court_plus_minus': 2.3,
            'other_turnovers': None,
            'passing_turnovers': 45,
            'percentage_field_goals_as_dunks': 0.018,
            'percentage_of_three_pointers_from_corner': 0.143,
            'percentage_shots_three_pointers': 0.14,
            'percentage_shots_two_pointers': 0.86,
            'percentage_sixteen_foot_plus_two_pointers': 0.068,
            'percentage_ten_to_sixteen_footers': 0.078,
            'percentage_three_to_ten_footers': 0.293,
            'percentage_zero_to_three_footers': 0.418,
            'personal_fouls': 208,
            'personal_fouls_per_poss': 6.0,
            'player_efficiency_rating': 21.5,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 796,
            'points_per_poss': 23.0,
            'points_generated_by_assists': 438,
            'position': 'C',
            'power_forward_percentage': 5,
            'salary': 1300000.0,
            'shooting_distance': 7.6,
            'shooting_fouls': 94,
            'shooting_fouls_drawn': 77,
            'shooting_guard_percentage': 0,
            'shots_blocked': 57,
            'small_forward_percentage': 0,
            'steal_percentage': 2.3,
            'steals': 79,
            'steals_per_poss': 2.3,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.14,
            'three_point_attempts': 84,
            'three_point_attempts_per_poss': 2.4,
            'three_point_percentage': 0.333,
            'three_point_shot_percentage_from_corner': 0.333,
            'three_pointers': 28,
            'three_pointers_assisted_percentage': 0.929,
            'three_pointers_per_poss': 0.8,
            'total_rebound_percentage': 17.9,
            'total_rebounds': 560,
            'total_rebounds_per_poss': 16.2,
            'true_shooting_percentage': 0.582,
            'turnover_percentage': 13.2,
            'turnovers': 104,
            'turnovers_per_poss': 3.0,
            'two_point_attempts': 516,
            'two_point_attempts_per_poss': 14.9,
            'two_point_percentage': 0.541,
            'two_pointers': 279,
            'two_pointers_per_poss': 8.1,
            'two_pointers_assisted_percentage': 0.595,
            'usage_percentage': 19.9,
            'value_over_replacement_player': 2.6,
            'weight': 284,
            'win_shares': 6.7,
            'win_shares_per_48_minutes': 0.185},
            {'and_ones': 27,
            'assist_percentage': 28.8,
            'assists': 359,
            'assists_per_poss': 8.6,
            'block_percentage': 2.1,
            'blocking_fouls': None,
            'blocks': 55,
            'blocks_per_poss': 1.3,
            'box_plus_minus': 7.3,
            'center_percentage': 95,
            'defensive_box_plus_minus': 1.4,
            'defensive_rebound_percentage': 27.2,
            'defensive_rebounds': 506,
            'defensive_rebounds_per_poss': 12.1,
            'defensive_win_shares': 2.0,
            'dunks': 23,
            'effective_field_goal_percentage': 0.605,
            'field_goal_attempts': 854,
            'field_goal_attempts_per_poss': 20.5,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.552,
            'field_goal_perc_ten_to_sixteen_feet': 0.53,
            'field_goal_perc_three_to_ten_feet': 0.624,
            'field_goal_perc_zero_to_three_feet': 0.674,
            'field_goal_percentage': 0.578,
            'field_goals': 494,
            'field_goals_per_poss': 11.8,
            'free_throw_attempt_rate': 0.267,
            'free_throw_attempts': 228,
            'free_throw_attempts_per_poss': 5.5,
            'free_throw_percentage': 0.825,
            'free_throws': 188,
            'free_throws_per_poss': 4.5,
            'games_played': 73,
            'games_started': 59,
            'half_court_heaves': 1,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 42,
            'minutes_played': 2038,
            'nationality': 'Serbia',
            'net_plus_minus': 11.5,
            'offensive_box_plus_minus': 5.9,
            'offensive_fouls': 24,
            'offensive_rebound_percentage': 11.6,
            'offensive_rebounds': 212,
            'offensive_rebounds_per_poss': 5.1,
            'offensive_win_shares': 7.7,
            'on_court_plus_minus': 5.6,
            'other_turnovers': None,
            'passing_turnovers': 89,
            'percentage_field_goals_as_dunks': 0.029,
            'percentage_of_three_pointers_from_corner': 0.072,
            'percentage_shots_three_pointers': 0.163,
            'percentage_shots_two_pointers': 0.837,
            'percentage_sixteen_foot_plus_two_pointers': 0.102,
            'percentage_ten_to_sixteen_footers': 0.097,
            'percentage_three_to_ten_footers': 0.293,
            'percentage_zero_to_three_footers': 0.349,
            'personal_fouls': 214,
            'personal_fouls_per_poss': 5.1,
            'player_efficiency_rating': 26.3,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 1221,
            'points_per_poss': 29.3,
            'points_generated_by_assists': 816,
            'position': 'C',
            'power_forward_percentage': 5,
            'salary': 1358500.0,
            'shooting_distance': 9.5,
            'shooting_fouls': 92,
            'shooting_fouls_drawn': 92,
            'shooting_guard_percentage': 0,
            'shots_blocked': 51,
            'small_forward_percentage': 0,
            'steal_percentage': 1.5,
            'steals': 61,
            'steals_per_poss': 1.5,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.163,
            'three_point_attempts': 139,
            'three_point_attempts_per_poss': 3.3,
            'three_point_percentage': 0.324,
            'three_point_shot_percentage_from_corner': 0.1,
            'three_pointers': 45,
            'three_pointers_assisted_percentage': 0.933,
            'three_pointers_per_poss': 1.1,
            'total_rebound_percentage': 19.5,
            'total_rebounds': 718,
            'total_rebounds_per_poss': 17.2,
            'true_shooting_percentage': 0.64,
            'turnover_percentage': 15.2,
            'turnovers': 171,
            'turnovers_per_poss': 4.1,
            'two_point_attempts': 715,
            'two_point_attempts_per_poss': 17.1,
            'two_point_percentage': 0.628,
            'two_pointers': 449,
            'two_pointers_per_poss': 10.8,
            'two_pointers_assisted_percentage': 0.566,
            'usage_percentage': 23.5,
            'value_over_replacement_player': 4.8,
            'weight': 284,
            'win_shares': 9.7,
            'win_shares_per_48_minutes': 0.228},
            {'and_ones': 43,
            'assist_percentage': 29.6,
            'assists': 458,
            'assists_per_poss': 9.3,
            'block_percentage': 2.1,
            'blocking_fouls': None,
            'blocks': 61,
            'blocks_per_poss': 1.2,
            'box_plus_minus': 6.9,
            'center_percentage': 100,
            'defensive_box_plus_minus': 1.6,
            'defensive_rebound_percentage': 27.9,
            'defensive_rebounds': 608,
            'defensive_rebounds_per_poss': 12.3,
            'defensive_win_shares': 2.9,
            'dunks': 8,
            'effective_field_goal_percentage': 0.554,
            'field_goal_attempts': 1010,
            'field_goal_attempts_per_poss': 20.5,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.443,
            'field_goal_perc_ten_to_sixteen_feet': 0.456,
            'field_goal_perc_three_to_ten_feet': 0.5,
            'field_goal_perc_zero_to_three_feet': 0.674,
            'field_goal_percentage': 0.499,
            'field_goals': 504,
            'field_goals_per_poss': 10.2,
            'free_throw_attempt_rate': 0.31,
            'free_throw_attempts': 313,
            'free_throw_attempts_per_poss': 6.4,
            'free_throw_percentage': 0.85,
            'free_throws': 266,
            'free_throws_per_poss': 5.4,
            'games_played': 75,
            'games_started': 73,
            'half_court_heaves': 3,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 53,
            'minutes_played': 2443,
            'nationality': 'Serbia',
            'net_plus_minus': 10.2,
            'offensive_box_plus_minus': 5.3,
            'offensive_fouls': 31,
            'offensive_rebound_percentage': 9.0,
            'offensive_rebounds': 195,
            'offensive_rebounds_per_poss': 4.0,
            'offensive_win_shares': 7.8,
            'on_court_plus_minus': 5.2,
            'other_turnovers': None,
            'passing_turnovers': 97,
            'percentage_field_goals_as_dunks': 0.009,
            'percentage_of_three_pointers_from_corner': 0.075,
            'percentage_shots_three_pointers': 0.277,
            'percentage_shots_two_pointers': 0.723,
            'percentage_sixteen_foot_plus_two_pointers': 0.096,
            'percentage_ten_to_sixteen_footers': 0.113,
            'percentage_three_to_ten_footers': 0.287,
            'percentage_zero_to_three_footers': 0.225,
            'personal_fouls': 212,
            'personal_fouls_per_poss': 4.3,
            'player_efficiency_rating': 24.4,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 1385,
            'points_per_poss': 28.1,
            'points_generated_by_assists': 1065,
            'position': 'C',
            'power_forward_percentage': 0,
            'salary': 1471382.0,
            'shooting_distance': 11.9,
            'shooting_fouls': 80,
            'shooting_fouls_drawn': 134,
            'shooting_guard_percentage': 0,
            'shots_blocked': 44,
            'small_forward_percentage': 0,
            'steal_percentage': 1.8,
            'steals': 90,
            'steals_per_poss': 1.8,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.277,
            'three_point_attempts': 280,
            'three_point_attempts_per_poss': 5.7,
            'three_point_percentage': 0.396,
            'three_point_shot_percentage_from_corner': 0.571,
            'three_pointers': 111,
            'three_pointers_assisted_percentage': 0.892,
            'three_pointers_per_poss': 2.3,
            'total_rebound_percentage': 18.5,
            'total_rebounds': 803,
            'total_rebounds_per_poss': 16.3,
            'true_shooting_percentage': 0.603,
            'turnover_percentage': 15.5,
            'turnovers': 210,
            'turnovers_per_poss': 4.3,
            'two_point_attempts': 730,
            'two_point_attempts_per_poss': 14.8,
            'two_point_percentage': 0.538,
            'two_pointers': 393,
            'two_pointers_per_poss': 8.0,
            'two_pointers_assisted_percentage': 0.542,
            'usage_percentage': 24.2,
            'value_over_replacement_player': 5.5,
            'weight': 284,
            'win_shares': 10.7,
            'win_shares_per_48_minutes': 0.211},
            {'and_ones': 44,
            'assist_percentage': 37.0,
            'assists': 580,
            'assists_per_poss': 11.4,
            'block_percentage': 1.9,
            'blocking_fouls': None,
            'blocks': 55,
            'blocks_per_poss': 1.1,
            'box_plus_minus': 9.1,
            'center_percentage': 100,
            'defensive_box_plus_minus': 2.9,
            'defensive_rebound_percentage': 27.6,
            'defensive_rebounds': 637,
            'defensive_rebounds_per_poss': 12.5,
            'defensive_win_shares': 4.3,
            'dunks': 11,
            'effective_field_goal_percentage': 0.545,
            'field_goal_attempts': 1206,
            'field_goal_attempts_per_poss': 23.7,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.346,
            'field_goal_perc_ten_to_sixteen_feet': 0.519,
            'field_goal_perc_three_to_ten_feet': 0.499,
            'field_goal_perc_zero_to_three_feet': 0.695,
            'field_goal_percentage': 0.511,
            'field_goals': 616,
            'field_goals_per_poss': 12.1,
            'free_throw_attempt_rate': 0.292,
            'free_throw_attempts': 352,
            'free_throw_attempts_per_poss': 6.9,
            'free_throw_percentage': 0.821,
            'free_throws': 289,
            'free_throws_per_poss': 5.7,
            'games_played': 80,
            'games_started': 80,
            'half_court_heaves': 4,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 65,
            'minutes_played': 2504,
            'nationality': 'Serbia',
            'net_plus_minus': 3.2,
            'offensive_box_plus_minus': 6.2,
            'offensive_fouls': 30,
            'offensive_rebound_percentage': 9.8,
            'offensive_rebounds': 228,
            'offensive_rebounds_per_poss': 4.5,
            'offensive_win_shares': 7.5,
            'on_court_plus_minus': 4.9,
            'other_turnovers': None,
            'passing_turnovers': 131,
            'percentage_field_goals_as_dunks': 0.009,
            'percentage_of_three_pointers_from_corner': 0.022,
            'percentage_shots_three_pointers': 0.224,
            'percentage_shots_two_pointers': 0.776,
            'percentage_sixteen_foot_plus_two_pointers': 0.067,
            'percentage_ten_to_sixteen_footers': 0.086,
            'percentage_three_to_ten_footers': 0.299,
            'percentage_zero_to_three_footers': 0.323,
            'personal_fouls': 228,
            'personal_fouls_per_poss': 4.5,
            'player_efficiency_rating': 26.3,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 1604,
            'points_per_poss': 31.5,
            'points_generated_by_assists': 1333,
            'position': 'C',
            'power_forward_percentage': 0,
            'salary': 24605181.0,
            'shooting_distance': 10.4,
            'shooting_fouls': 94,
            'shooting_fouls_drawn': 135,
            'shooting_guard_percentage': 0,
            'shots_blocked': 67,
            'small_forward_percentage': 0,
            'steal_percentage': 2.1,
            'steals': 108,
            'steals_per_poss': 2.1,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.224,
            'three_point_attempts': 270,
            'three_point_attempts_per_poss': 5.3,
            'three_point_percentage': 0.307,
            'three_point_shot_percentage_from_corner': 0.333,
            'three_pointers': 83,
            'three_pointers_assisted_percentage': 0.916,
            'three_pointers_per_poss': 1.6,
            'total_rebound_percentage': 18.7,
            'total_rebounds': 865,
            'total_rebounds_per_poss': 17.0,
            'true_shooting_percentage': 0.589,
            'turnover_percentage': 15.4,
            'turnovers': 248,
            'turnovers_per_poss': 4.9,
            'two_point_attempts': 936,
            'two_point_attempts_per_poss': 18.4,
            'two_point_percentage': 0.569,
            'two_pointers': 533,
            'two_pointers_per_poss': 10.5,
            'two_pointers_assisted_percentage': 0.48,
            'usage_percentage': 27.4,
            'value_over_replacement_player': 7.0,
            'weight': 284,
            'win_shares': 11.8,
            'win_shares_per_48_minutes': 0.226},
            {'and_ones': 26,
            'assist_percentage': 35.2,
            'assists': 512,
            'assists_per_poss': 10.8,
            'block_percentage': 1.7,
            'blocking_fouls': None,
            'blocks': 44,
            'blocks_per_poss': 0.9,
            'box_plus_minus': 7.4,
            'center_percentage': 100,
            'defensive_box_plus_minus': 2.0,
            'defensive_rebound_percentage': 26.1,
            'defensive_rebounds': 545,
            'defensive_rebounds_per_poss': 11.5,
            'defensive_win_shares': 3.1,
            'dunks': 15,
            'effective_field_goal_percentage': 0.565,
            'field_goal_attempts': 1071,
            'field_goal_attempts_per_poss': 22.7,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.435,
            'field_goal_perc_ten_to_sixteen_feet': 0.49,
            'field_goal_perc_three_to_ten_feet': 0.599,
            'field_goal_perc_zero_to_three_feet': 0.724,
            'field_goal_percentage': 0.528,
            'field_goals': 565,
            'field_goals_per_poss': 12.0,
            'free_throw_attempt_rate': 0.281,
            'free_throw_attempts': 301,
            'free_throw_attempts_per_poss': 6.4,
            'free_throw_percentage': 0.817,
            'free_throws': 246,
            'free_throws_per_poss': 5.2,
            'games_played': 73,
            'games_started': 73,
            'half_court_heaves': 4,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 54,
            'minutes_played': 2336,
            'nationality': 'Serbia',
            'net_plus_minus': 6.2,
            'offensive_box_plus_minus': 5.5,
            'offensive_fouls': 20,
            'offensive_rebound_percentage': 8.0,
            'offensive_rebounds': 166,
            'offensive_rebounds_per_poss': 3.5,
            'offensive_win_shares': 6.7,
            'on_court_plus_minus': 4.4,
            'other_turnovers': None,
            'passing_turnovers': 135,
            'percentage_field_goals_as_dunks': 0.014,
            'percentage_of_three_pointers_from_corner': 0.039,
            'percentage_shots_three_pointers': 0.238,
            'percentage_shots_two_pointers': 0.762,
            'percentage_sixteen_foot_plus_two_pointers': 0.107,
            'percentage_ten_to_sixteen_footers': 0.143,
            'percentage_three_to_ten_footers': 0.275,
            'percentage_zero_to_three_footers': 0.237,
            'personal_fouls': 222,
            'personal_fouls_per_poss': 4.7,
            'player_efficiency_rating': 24.9,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 1456,
            'points_per_poss': 30.8,
            'points_generated_by_assists': 1171,
            'position': 'C',
            'power_forward_percentage': 0,
            'salary': 26573595.0,
            'shooting_distance': 12.0,
            'shooting_fouls': 98,
            'shooting_fouls_drawn': 107,
            'shooting_guard_percentage': 0,
            'shots_blocked': 32,
            'small_forward_percentage': 0,
            'steal_percentage': 1.8,
            'steals': 85,
            'steals_per_poss': 1.8,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.238,
            'three_point_attempts': 255,
            'three_point_attempts_per_poss': 5.4,
            'three_point_percentage': 0.314,
            'three_point_shot_percentage_from_corner': 0.5,
            'three_pointers': 80,
            'three_pointers_assisted_percentage': 0.85,
            'three_pointers_per_poss': 1.7,
            'total_rebound_percentage': 17.1,
            'total_rebounds': 711,
            'total_rebounds_per_poss': 15.0,
            'true_shooting_percentage': 0.605,
            'turnover_percentage': 15.8,
            'turnovers': 226,
            'turnovers_per_poss': 4.8,
            'two_point_attempts': 816,
            'two_point_attempts_per_poss': 17.3,
            'two_point_percentage': 0.594,
            'two_pointers': 485,
            'two_pointers_per_poss': 10.3,
            'two_pointers_assisted_percentage': 0.511,
            'usage_percentage': 26.6,
            'value_over_replacement_player': 5.5,
            'weight': 284,
            'win_shares': 9.8,
            'win_shares_per_48_minutes': 0.202},
            {'and_ones': 38,
            'assist_percentage': 40.4,
            'assists': 599,
            'assists_per_poss': 11.9,
            'block_percentage': 1.9,
            'blocking_fouls': None,
            'blocks': 48,
            'blocks_per_poss': 1.0,
            'box_plus_minus': 12.1,
            'center_percentage': 99,
            'defensive_box_plus_minus': 3.0,
            'defensive_rebound_percentage': 26.1,
            'defensive_rebounds': 575,
            'defensive_rebounds_per_poss': 11.4,
            'defensive_win_shares': 3.4,
            'dunks': 45,
            'effective_field_goal_percentage': 0.602,
            'field_goal_attempts': 1293,
            'field_goal_attempts_per_poss': 25.7,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.528,
            'field_goal_perc_ten_to_sixteen_feet': 0.481,
            'field_goal_perc_three_to_ten_feet': 0.572,
            'field_goal_perc_zero_to_three_feet': 0.753,
            'field_goal_percentage': 0.566,
            'field_goals': 732,
            'field_goals_per_poss': 14.5,
            'free_throw_attempt_rate': 0.305,
            'free_throw_attempts': 394,
            'free_throw_attempts_per_poss': 7.8,
            'free_throw_percentage': 0.868,
            'free_throws': 342,
            'free_throws_per_poss': 6.8,
            'games_played': 72,
            'games_started': 72,
            'half_court_heaves': 3,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 63,
            'minutes_played': 2488,
            'nationality': 'Serbia',
            'net_plus_minus': 6.4,
            'offensive_box_plus_minus': 9.1,
            'offensive_fouls': 16,
            'offensive_rebound_percentage': 9.4,
            'offensive_rebounds': 205,
            'offensive_rebounds_per_poss': 4.1,
            'offensive_win_shares': 12.2,
            'on_court_plus_minus': 6.6,
            'other_turnovers': None,
            'passing_turnovers': 130,
            'percentage_field_goals_as_dunks': 0.037,
            'percentage_of_three_pointers_from_corner': 0.034,
            'percentage_shots_three_pointers': 0.183,
            'percentage_shots_two_pointers': 0.817,
            'percentage_sixteen_foot_plus_two_pointers': 0.082,
            'percentage_ten_to_sixteen_footers': 0.14,
            'percentage_three_to_ten_footers': 0.35,
            'percentage_zero_to_three_footers': 0.244,
            'personal_fouls': 192,
            'personal_fouls_per_poss': 3.8,
            'player_efficiency_rating': 31.3,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 1898,
            'points_per_poss': 37.7,
            'points_generated_by_assists': 1410,
            'position': 'C',
            'power_forward_percentage': 1,
            'salary': 29542010.0,
            'shooting_distance': 10.6,
            'shooting_fouls': 102,
            'shooting_fouls_drawn': 145,
            'shooting_guard_percentage': 0,
            'shots_blocked': 62,
            'small_forward_percentage': 0,
            'steal_percentage': 1.9,
            'steals': 95,
            'steals_per_poss': 1.9,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.183,
            'three_point_attempts': 237,
            'three_point_attempts_per_poss': 4.7,
            'three_point_percentage': 0.388,
            'three_point_shot_percentage_from_corner': 0.375,
            'three_pointers': 92,
            'three_pointers_assisted_percentage': 0.967,
            'three_pointers_per_poss': 1.8,
            'total_rebound_percentage': 17.8,
            'total_rebounds': 780,
            'total_rebounds_per_poss': 15.5,
            'true_shooting_percentage': 0.647,
            'turnover_percentage': 13.1,
            'turnovers': 222,
            'turnovers_per_poss': 4.4,
            'two_point_attempts': 1056,
            'two_point_attempts_per_poss': 21.0,
            'two_point_percentage': 0.606,
            'two_pointers': 640,
            'two_pointers_per_poss': 12.7,
            'two_pointers_assisted_percentage': 0.484,
            'usage_percentage': 29.6,
            'value_over_replacement_player': 8.8,
            'weight': 284,
            'win_shares': 15.6,
            'win_shares_per_48_minutes': 0.301},
            {'and_ones': 72,
            'assist_percentage': 42.6,
            'assists': 584,
            'assists_per_poss': 11.6,
            'block_percentage': 2.3,
            'blocking_fouls': None,
            'blocks': 63,
            'blocks_per_poss': 1.2,
            'box_plus_minus': 13.7,
            'center_percentage': 100,
            'defensive_box_plus_minus': 4.5,
            'defensive_rebound_percentage': 35.5,
            'defensive_rebounds': 813,
            'defensive_rebounds_per_poss': 16.1,
            'defensive_win_shares': 4.5,
            'dunks': 31,
            'effective_field_goal_percentage': 0.62,
            'field_goal_attempts': 1311,
            'field_goal_attempts_per_poss': 26.0,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.467,
            'field_goal_perc_ten_to_sixteen_feet': 0.565,
            'field_goal_perc_three_to_ten_feet': 0.606,
            'field_goal_perc_zero_to_three_feet': 0.776,
            'field_goal_percentage': 0.583,
            'field_goals': 764,
            'field_goals_per_poss': 15.1,
            'free_throw_attempt_rate': 0.357,
            'free_throw_attempts': 468,
            'free_throw_attempts_per_poss': 9.3,
            'free_throw_percentage': 0.81,
            'free_throws': 379,
            'free_throws_per_poss': 7.5,
            'games_played': 74,
            'games_started': 74,
            'half_court_heaves': 3,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 76,
            'minutes_played': 2476,
            'nationality': 'Serbia',
            'net_plus_minus': 16.4,
            'offensive_box_plus_minus': 9.2,
            'offensive_fouls': 21,
            'offensive_rebound_percentage': 9.6,
            'offensive_rebounds': 206,
            'offensive_rebounds_per_poss': 4.1,
            'offensive_win_shares': 10.8,
            'on_court_plus_minus': 8.4,
            'other_turnovers': None,
            'passing_turnovers': 173,
            'percentage_field_goals_as_dunks': 0.025,
            'percentage_of_three_pointers_from_corner': 0.038,
            'percentage_shots_three_pointers': 0.22,
            'percentage_shots_two_pointers': 0.78,
            'percentage_sixteen_foot_plus_two_pointers': 0.046,
            'percentage_ten_to_sixteen_footers': 0.082,
            'percentage_three_to_ten_footers': 0.384,
            'percentage_zero_to_three_footers': 0.268,
            'personal_fouls': 191,
            'personal_fouls_per_poss': 3.8,
            'player_efficiency_rating': 32.8,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 2004,
            'points_per_poss': 39.7,
            'points_generated_by_assists': 1356,
            'position': 'C',
            'power_forward_percentage': 0,
            'salary': 30510423.0,
            'shooting_distance': 10.2,
            'shooting_fouls': 101,
            'shooting_fouls_drawn': 188,
            'shooting_guard_percentage': 0,
            'shots_blocked': 66,
            'small_forward_percentage': 0,
            'steal_percentage': 2.2,
            'steals': 109,
            'steals_per_poss': 2.2,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.22,
            'three_point_attempts': 288,
            'three_point_attempts_per_poss': 5.7,
            'three_point_percentage': 0.337,
            'three_point_shot_percentage_from_corner': 0.273,
            'three_pointers': 97,
            'three_pointers_assisted_percentage': 0.918,
            'three_pointers_per_poss': 1.9,
            'total_rebound_percentage': 23.0,
            'total_rebounds': 1019,
            'total_rebounds_per_poss': 20.2,
            'true_shooting_percentage': 0.661,
            'turnover_percentage': 15.6,
            'turnovers': 281,
            'turnovers_per_poss': 5.6,
            'two_point_attempts': 1023,
            'two_point_attempts_per_poss': 20.3,
            'two_point_percentage': 0.652,
            'two_pointers': 667,
            'two_pointers_per_poss': 13.2,
            'two_pointers_assisted_percentage': 0.58,
            'usage_percentage': 31.9,
            'value_over_replacement_player': 9.8,
            'weight': 284,
            'win_shares': 15.2,
            'win_shares_per_48_minutes': 0.296},
            {'and_ones': 6,
            'assist_percentage': 45.2,
            'assists': 116,
            'assists_per_poss': 13.8,
            'block_percentage': 1.8,
            'blocking_fouls': None,
            'blocks': 8,
            'blocks_per_poss': 1.0,
            'box_plus_minus': 10.7,
            'center_percentage': 100,
            'defensive_box_plus_minus': 4.0,
            'defensive_rebound_percentage': 28.9,
            'defensive_rebounds': 103,
            'defensive_rebounds_per_poss': 12.3,
            'defensive_win_shares': 0.5,
            'dunks': 6,
            'effective_field_goal_percentage': 0.629,
            'field_goal_attempts': 170,
            'field_goal_attempts_per_poss': 20.3,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.8,
            'field_goal_perc_ten_to_sixteen_feet': 0.462,
            'field_goal_perc_three_to_ten_feet': 0.618,
            'field_goal_perc_zero_to_three_feet': 0.769,
            'field_goal_percentage': 0.606,
            'field_goals': 103,
            'field_goals_per_poss': 12.3,
            'free_throw_attempt_rate': 0.376,
            'free_throw_attempts': 64,
            'free_throw_attempts_per_poss': 7.6,
            'free_throw_percentage': 0.875,
            'free_throws': 56,
            'free_throws_per_poss': 6.7,
            'games_played': 13,
            'games_started': 13,
            'half_court_heaves': 0,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 7,
            'minutes_played': 404,
            'nationality': 'Serbia',
            'net_plus_minus': 26.1,
            'offensive_box_plus_minus': 6.7,
            'offensive_fouls': 7,
            'offensive_rebound_percentage': 5.6,
            'offensive_rebounds': 20,
            'offensive_rebounds_per_poss': 2.4,
            'offensive_win_shares': 1.8,
            'on_court_plus_minus': 12.3,
            'other_turnovers': None,
            'passing_turnovers': 22,
            'percentage_field_goals_as_dunks': 0.041,
            'percentage_of_three_pointers_from_corner': 0.036,
            'percentage_shots_three_pointers': 0.165,
            'percentage_shots_two_pointers': 0.835,
            'percentage_sixteen_foot_plus_two_pointers': 0.029,
            'percentage_ten_to_sixteen_footers': 0.076,
            'percentage_three_to_ten_footers': 0.324,
            'percentage_zero_to_three_footers': 0.229,
            'personal_fouls': 35,
            'personal_fouls_per_poss': 4.2,
            'player_efficiency_rating': 29.7,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 270,
            'points_per_poss': 32.2,
            'points_generated_by_assists': 272,
            'position': 'C',
            'power_forward_percentage': 0,
            'salary': None,
            'shooting_distance': 6.8,
            'shooting_fouls': 10,
            'shooting_fouls_drawn': 21,
            'shooting_guard_percentage': 0,
            'shots_blocked': 4,
            'small_forward_percentage': 0,
            'steal_percentage': 2.3,
            'steals': 19,
            'steals_per_poss': 2.3,
            'take_fouls': None,
            'team_abbreviation': 'DEN',
            'three_point_attempt_rate': 0.165,
            'three_point_attempts': 28,
            'three_point_attempts_per_poss': 3.3,
            'three_point_percentage': 0.286,
            'three_point_shot_percentage_from_corner': 0.0,
            'three_pointers': 8,
            'three_pointers_assisted_percentage': 0.75,
            'three_pointers_per_poss': 1.0,
            'total_rebound_percentage': 17.3,
            'total_rebounds': 123,
            'total_rebounds_per_poss': 14.7,
            'true_shooting_percentage': 0.681,
            'turnover_percentage': 17.1,
            'turnovers': 41,
            'turnovers_per_poss': 4.9,
            'two_point_attempts': 142,
            'two_point_attempts_per_poss': 16.9,
            'two_point_percentage': 0.669,
            'two_pointers': 95,
            'two_pointers_per_poss': 11.3,
            'two_pointers_assisted_percentage': 0.526,
            'usage_percentage': 25.5,
            'value_over_replacement_player': 1.3,
            'weight': 284,
            'win_shares': 2.4,
            'win_shares_per_48_minutes': 0.28},
            {'and_ones': 280,
            'assist_percentage': 34.2,
            'assists': 3397,
            'assists_per_poss': 10.2,
            'block_percentage': 2.0,
            'blocking_fouls': None,
            'blocks': 384,
            'blocks_per_poss': 1.2,
            'box_plus_minus': 8.9,
            'center_percentage': 99,
            'defensive_box_plus_minus': 2.5,
            'defensive_rebound_percentage': 28.1,
            'defensive_rebounds': 4166,
            'defensive_rebounds_per_poss': 12.5,
            'defensive_win_shares': 23.0,
            'dunks': 150,
            'effective_field_goal_percentage': 0.58,
            'field_goal_attempts': 7515,
            'field_goal_attempts_per_poss': 22.6,
            'field_goal_perc_sixteen_foot_plus_two_pointers': 0.463,
            'field_goal_perc_ten_to_sixteen_feet': 0.498,
            'field_goal_perc_three_to_ten_feet': 0.562,
            'field_goal_perc_zero_to_three_feet': 0.708,
            'field_goal_percentage': 0.544,
            'field_goals': 4085,
            'field_goals_per_poss': 12.3,
            'free_throw_attempt_rate': 0.307,
            'free_throw_attempts': 2310,
            'free_throw_attempts_per_poss': 6.9,
            'free_throw_percentage': 0.831,
            'free_throws': 1920,
            'free_throws_per_poss': 5.8,
            'games_played': 540,
            'games_started': 499,
            'half_court_heaves': 18,
            'half_court_heaves_made': 0,
            'height': 'Nikola Jokić',
            'lost_ball_turnovers': 388,
            'minutes_played': 16422,
            'nationality': 'Serbia',
            'net_plus_minus': 9.4,
            'offensive_box_plus_minus': 6.5,
            'offensive_fouls': 164,
            'offensive_rebound_percentage': 9.6,
            'offensive_rebounds': 1413,
            'offensive_rebounds_per_poss': 4.2,
            'offensive_win_shares': 59.0,
            'on_court_plus_minus': 5.7,
            'other_turnovers': None,
            'passing_turnovers': 822,
            'percentage_field_goals_as_dunks': 0.021,
            'percentage_of_three_pointers_from_corner': 0.05,
            'percentage_shots_three_pointers': 0.21,
            'percentage_shots_two_pointers': 0.79,
            'percentage_sixteen_foot_plus_two_pointers': 0.079,
            'percentage_ten_to_sixteen_footers': 0.107,
            'percentage_three_to_ten_footers': 0.317,
            'percentage_zero_to_three_footers': 0.283,
            'personal_fouls': 1502,
            'personal_fouls_per_poss': 4.5,
            'player_efficiency_rating': 27.2,
            'player_id': 'jokicni01',
            'point_guard_percentage': 0,
            'points': 10634,
            'points_per_poss': 31.9,
            'points_generated_by_assists': 7861,
            'position': 'C',
            'power_forward_percentage': 1,
            'salary': 115361091.0,
            'shooting_distance': 9.9,
            'shooting_fouls': 671,
            'shooting_fouls_drawn': 899,
            'shooting_guard_percentage': 0,
            'shots_blocked': 383,
            'small_forward_percentage': 0,
            'steal_percentage': 1.9,
            'steals': 646,
            'steals_per_poss': 1.9,
            'take_fouls': None,
            'team_abbreviation': '',
            'three_point_attempt_rate': 0.21,
            'three_point_attempts': 1581,
            'three_point_attempts_per_poss': 4.7,
            'three_point_percentage': 0.344,
            'three_point_shot_percentage_from_corner': 0.38,
            'three_pointers': 544,
            'three_pointers_assisted_percentage': 0.91,
            'three_pointers_per_poss': 1.6,
            'total_rebound_percentage': 18.9,
            'total_rebounds': 5579,
            'total_rebounds_per_poss': 16.8,
            'true_shooting_percentage': 0.623,
            'turnover_percentage': 15.0,
            'turnovers': 1503,
            'turnovers_per_poss': 4.5,
            'two_point_attempts': 5934,
            'two_point_attempts_per_poss': 17.8,
            'two_point_percentage': 0.597,
            'two_pointers': 3541,
            'two_pointers_per_poss': 10.6,
            'two_pointers_assisted_percentage': 0.532,
            'usage_percentage': 26.5,
            'value_over_replacement_player': 45.3,
            'weight': 284,
            'win_shares': 82.0,
            'win_shares_per_48_minutes': 0.24
            }
        ]
        indices = ['2015-16', '2016-17', '2017-18', '2018-19',
                   '2019-20', '2020-21', '2021-22', '2022-23', 'Career']

        df = pd.DataFrame(dataframe, index=indices)
        player = self.player('')

        # Pandas doesn't natively allow comparisons of DataFrames.
        # Concatenating the two DataFrames (the one generated during the test
        # and the expected one above) and dropping duplicate rows leaves only
        # the rows that are unique between the two frames. This allows a quick
        # check of the DataFrame to see if it is empty - if so, all rows are
        # duplicates, and they are equal.
        frames = [df, player.dataframe]
        df1 = pd.concat(frames).drop_duplicates(keep=False)

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_nba_player_with_no_stats_handled_without_error(self, *args, **kwargs):
        player = Player('bolbo01')

        assert player.name == 'Bol Bol'

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_nba_player_string_representation(self, *args, **kwargs):
        # Request the career stats
        player = self.player('')

        assert player.__repr__() == 'Nikola Jokić (jokicni01)'


class TestNBARoster:
    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_roster_class_pulls_all_player_stats(self, *args, **kwargs):
        flexmock(utils) \
            .should_receive('_find_year_for_season') \
            .and_return(YEAR)
        roster = Roster('DEN')

        assert len(roster.players) == 22

        roster_players = [player.name for player in roster.players]
        for player in ['Will Barton', 'Bol Bol', 'Nikola Jokić']:
            assert player in roster_players

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_bad_url_raises_value_error(self, *args, **kwargs):
        with pytest.raises(ValueError):
            roster = Roster('BAD')

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_roster_from_team_class(self, *args, **kwargs):
        flexmock(Team) \
            .should_receive('_parse_team_data') \
            .and_return(None)
        team = Team(None, 1, YEAR)
        mock_abbreviation = mock.PropertyMock(return_value='DEN')
        type(team)._abbreviation = mock_abbreviation

        assert len(team.roster.players) == 22

        roster_players = [player.name for player in team.roster.players]
        for player in ['Will Barton', 'Bol Bol', 'Nikola Jokić']:
            assert player in roster_players

        type(team)._abbreviation = None

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_roster_class_with_slim_parameter(self, *args, **kwargs):
        flexmock(utils) \
            .should_receive('_find_year_for_season') \
            .and_return(YEAR)
        roster = Roster('DEN', slim=True)

        assert len(roster.players) == 22
        assert roster.players == {
            'bartowi01': 'Will Barton',
            'bolbo01': 'Bol Bol',
            'campafa01': 'Facundo Campazzo',
            'cancavl01': 'Vlatko Čančar',
            'cornepe01': 'Petr Cornelie',
            'couside01': 'DeMarcus Cousins',
            'doziepj01': 'PJ Dozier',
            'ennisja01': 'James Ennis III',
            'forbebr01': 'Bryn Forbes',
            'gordoaa01': 'Aaron Gordon',
            'greenja01': 'JaMychal Green',
            'greenje02': 'Jeff Green',
            'howarma02': 'Markus Howard',
            'hylanbo01': 'Bones Hyland',
            'jokicni01': 'Nikola Jokić',
            'jonesca03': 'Carlik Jones',
            'morrimo01': 'Monte Morris',
            'nnajize01': 'Zeke Nnaji',
            'portemi01': 'Michael Porter Jr.',
            'reedda01': 'Davon Reed',
            'riverau01': 'Austin Rivers',
            'tuckera01': 'Rayjon Tucker'
        }
        try:
            roster
        except AttributeError:
            pytest.fail('Roster string representation is not right!')
        

    @mock.patch('requests.head', side_effect=mock_request)
    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_invalid_default_year_reverts_to_previous_year(self,
                                                           *args,
                                                           **kwargs):
        flexmock(utils) \
            .should_receive('_find_year_for_season') \
            .and_return(2090)

        roster = Roster('DEN')

        assert len(roster.players) == 22

        roster_players = [player.name for player in roster.players]
        for player in ['Nikola Jokić']:
            assert player in roster_players

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_empty_rows_are_skipped(self, *args, **kwargs):
        flexmock(utils) \
            .should_receive('_find_year_for_season') \
            .and_return(YEAR)
        flexmock(Roster) \
            .should_receive('_get_id') \
            .and_return(None)

        roster = Roster('DEN')

        assert len(roster.players) == 0

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_roster_class_string_representation(self, *args, **kwargs):
        expected = """Will Barton (bartowi01)
Bol Bol (bolbo01)
None (campafa01)
None (cancavl01)
None (cornepe01)
None (couside01)
None (doziepj01)
None (ennisja01)
None (forbebr01)
None (gordoaa01)
None (greenja01)
None (greenje02)
None (howarma02)
None (hylanbo01)
Nikola Jokić (jokicni01)
None (jonesca03)
None (morrimo01)
None (nnajize01)
None (portemi01)
None (reedda01)
None (riverau01)
None (tuckera01)"""

        flexmock(utils) \
            .should_receive('_find_year_for_season') \
            .and_return(YEAR)
        roster = Roster('DEN')
        assert roster.__repr__() == expected

    @mock.patch('sports.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_coach(self, *args, **kwargs):
        assert "Michael Malone" == Roster('DEN').coach
