import mock
import os
import pandas as pd
from datetime import datetime
from flexmock import flexmock
from sportsipy import utils
from sportsipy.constants import AWAY
from sportsipy.ncaaf.constants import BOXSCORE_URL, BOXSCORES_URL
from sportsipy.ncaaf.boxscore import Boxscore, Boxscores
from pyquery import PyQuery as pq
from ..utils import read_file


MONTH = 10
YEAR = 2020

BOXSCORE = '2020-09-12-wake-forest'


def mock_pyquery(url):
    if url == BOXSCORES_URL % (9, 12, 2020):
        return read_file('boxscores-9-12-2020.html', 'ncaaf', 'boxscore')
    if url == BOXSCORES_URL % (9, 13, 2020):
        return read_file('boxscores-9-13-2020.html', 'ncaaf', 'boxscore')
    boxscore = read_file('%s.html' % BOXSCORE, 'ncaaf', 'boxscore')
    return boxscore


class MockDateTime:
    def __init__(self, year, month):
        self.year = year
        self.month = month


class TestNCAAFBoxscore:
    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def setup_method(self, *args, **kwargs):
        self.results = {
            'date': 'Saturday Sep 12, 2020',
            'time': '7:30 PM ET',
            'stadium': '',
            'winner': AWAY,
            'winning_name': 'Clemson',
            'winning_abbr': 'CLEMSON',
            'losing_name': 'Wake Forest',
            'losing_abbr': 'WAKE-FOREST',
            'away_points': 37,
            'away_first_downs': 27,
            'away_rush_attempts': 46,
            'away_rush_yards': 185,
            'away_rush_touchdowns': 3,
            'away_pass_completions': 26,
            'away_pass_attempts': 36,
            'away_pass_yards': 376,
            'away_pass_touchdowns': 1,
            'away_interceptions': 1,
            'away_total_yards': 561,
            'away_fumbles': 0,
            'away_fumbles_lost': 0,
            'away_turnovers': 1,
            'away_penalties': 5,
            'away_yards_from_penalties': 55,
            'home_points': 13,
            'home_first_downs': 15,
            'home_rush_attempts': 34,
            'home_rush_yards': 37,
            'home_rush_touchdowns': 0,
            'home_pass_completions': 19,
            'home_pass_attempts': 38,
            'home_pass_yards': 293,
            'home_pass_touchdowns': 1,
            'home_interceptions': 0,
            'home_total_yards': 330,
            'home_fumbles': 0,
            'home_fumbles_lost': 0,
            'home_turnovers': 0,
            'home_penalties': 1,
            'home_yards_from_penalties': 6
        }
        flexmock(utils) \
            .should_receive('_todays_date') \
            .and_return(MockDateTime(YEAR, MONTH))

        self.boxscore = Boxscore(BOXSCORE)

    def test_ncaaf_boxscore_returns_requested_boxscore(self):
        for attribute, value in self.results.items():
            assert getattr(self.boxscore, attribute) == value
        assert getattr(self.boxscore, 'summary') == {
            'away': [14, 13, 10, 0],
            'home': [0, 0, 3, 10]
        }

    def test_invalid_url_yields_empty_class(self):
        flexmock(Boxscore) \
            .should_receive('_retrieve_html_page') \
            .and_return(None)

        boxscore = Boxscore(BOXSCORE)

        for key, value in boxscore.__dict__.items():
            if key == '_uri':
                continue
            assert value is None

    def test_ncaaf_boxscore_dataframe_returns_dataframe_of_all_values(self):
        df = pd.DataFrame([self.results], index=[BOXSCORE])

        # Pandas doesn't natively allow comparisons of DataFrames.
        # Concatenating the two DataFrames (the one generated during the test
        # and the expected one above) and dropping duplicate rows leaves only
        # the rows that are unique between the two frames. This allows a quick
        # check of the DataFrame to see if it is empty - if so, all rows are
        # duplicates, and they are equal.
        frames = [df, self.boxscore.dataframe]
        df1 = pd.concat(frames).drop_duplicates(keep=False)

        assert df1.empty

    def test_ncaaf_boxscore_players(self):
        boxscore = self.boxscore

        assert len(boxscore.home_players) == 37
        assert len(boxscore.away_players) == 45

        for player in boxscore.home_players:
            assert not player.dataframe.empty
        for player in boxscore.away_players:
            assert not player.dataframe.empty

    def test_ncaaf_boxscore_string_representation(self):
        expected = ('Boxscore for Clemson at Wake Forest '
                    '(Saturday Sep 12, 2020)')

        assert self.boxscore.__repr__() == expected


class TestNCAAFBoxscores:
    def setup_method(self):
        self.expected = {
            '9-12-2020': [
                {'away_abbr': 'charlotte',
                'away_name': 'Charlotte',
                'away_rank': None,
                'away_score': 20,
                'boxscore': '2020-09-12-appalachian-state',
                'home_abbr': 'appalachian-state',
                'home_name': 'Appalachian State',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'charlotte',
                'losing_name': 'Charlotte',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'appalachian-state',
                'winning_name': 'Appalachian State'},
                {'away_abbr': 'louisiana-monroe',
                'away_name': 'Louisiana-Monroe',
                'away_rank': None,
                'away_score': 7,
                'boxscore': '2020-09-12-army',
                'home_abbr': 'army',
                'home_name': 'Army',
                'home_rank': None,
                'home_score': 37,
                'losing_abbr': 'louisiana-monroe',
                'losing_name': 'Louisiana-Monroe',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'army',
                'winning_name': 'Army'},
                {'away_abbr': 'georgia-tech',
                'away_name': 'Georgia Tech',
                'away_rank': None,
                'away_score': 16,
                'boxscore': '2020-09-12-florida-state',
                'home_abbr': 'florida-state',
                'home_name': 'Florida State',
                'home_rank': None,
                'home_score': 13,
                'losing_abbr': 'florida-state',
                'losing_name': 'Florida State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'georgia-tech',
                'winning_name': 'Georgia Tech'},
                {'away_abbr': 'Campbell',
                'away_name': 'Campbell',
                'away_rank': None,
                'away_score': 26,
                'boxscore': '2020-09-12-georgia-southern',
                'home_abbr': 'georgia-southern',
                'home_name': 'Georgia Southern',
                'home_rank': None,
                'home_score': 27,
                'losing_abbr': 'Campbell',
                'losing_name': 'Campbell',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'georgia-southern',
                'winning_name': 'Georgia Southern'},
                {'away_abbr': 'louisiana-lafayette',
                'away_name': 'Louisiana',
                'away_rank': None,
                'away_score': 31,
                'boxscore': '2020-09-12-iowa-state',
                'home_abbr': 'iowa-state',
                'home_name': 'Iowa State',
                'home_rank': 23,
                'home_score': 14,
                'losing_abbr': 'iowa-state',
                'losing_name': 'Iowa State',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'louisiana-lafayette',
                'winning_name': 'Louisiana'},
                {'away_abbr': 'coastal-carolina',
                'away_name': 'Coastal Carolina',
                'away_rank': None,
                'away_score': 38,
                'boxscore': '2020-09-12-kansas',
                'home_abbr': 'kansas',
                'home_name': 'Kansas',
                'home_rank': None,
                'home_score': 23,
                'losing_abbr': 'kansas',
                'losing_name': 'Kansas',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'coastal-carolina',
                'winning_name': 'Coastal Carolina'},
                {'away_abbr': 'arkansas-state',
                'away_name': 'Arkansas State',
                'away_rank': None,
                'away_score': 35,
                'boxscore': '2020-09-12-kansas-state',
                'home_abbr': 'kansas-state',
                'home_name': 'Kansas State',
                'home_rank': None,
                'home_score': 31,
                'losing_abbr': 'kansas-state',
                'losing_name': 'Kansas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'arkansas-state',
                'winning_name': 'Arkansas State'},
                {'away_abbr': 'western-kentucky',
                'away_name': 'Western Kentucky',
                'away_rank': None,
                'away_score': 21,
                'boxscore': '2020-09-12-louisville',
                'home_abbr': 'louisville',
                'home_name': 'Louisville',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'western-kentucky',
                'losing_name': 'Western Kentucky',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'louisville',
                'winning_name': 'Louisville'},
                {'away_abbr': 'syracuse',
                'away_name': 'Syracuse',
                'away_rank': None,
                'away_score': 6,
                'boxscore': '2020-09-12-north-carolina',
                'home_abbr': 'north-carolina',
                'home_name': 'North Carolina',
                'home_rank': 18,
                'home_score': 31,
                'losing_abbr': 'syracuse',
                'losing_name': 'Syracuse',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'north-carolina',
                'winning_name': 'North Carolina'},
                {'away_abbr': 'duke',
                'away_name': 'Duke',
                'away_rank': None,
                'away_score': 13,
                'boxscore': '2020-09-12-notre-dame',
                'home_abbr': 'notre-dame',
                'home_name': 'Notre Dame',
                'home_rank': 10,
                'home_score': 27,
                'losing_abbr': 'duke',
                'losing_name': 'Duke',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'notre-dame',
                'winning_name': 'Notre Dame'},
                {'away_abbr': 'Missouri State',
                'away_name': 'Missouri State',
                'away_rank': None,
                'away_score': 0,
                'boxscore': '2020-09-12-oklahoma',
                'home_abbr': 'oklahoma',
                'home_name': 'Oklahoma',
                'home_rank': 5,
                'home_score': 48,
                'losing_abbr': None,
                'losing_name': None,
                'non_di': True,
                'top_25': True,
                'winning_abbr': None,
                'winning_name': None},
                {'away_abbr': 'Austin Peay',
                'away_name': 'Austin Peay',
                'away_rank': None,
                'away_score': 0,
                'boxscore': '2020-09-12-pittsburgh',
                'home_abbr': 'pittsburgh',
                'home_name': 'Pitt',
                'home_rank': None,
                'home_score': 55,
                'losing_abbr': None,
                'losing_name': None,
                'non_di': True,
                'top_25': False,
                'winning_abbr': None,
                'winning_name': None},
                {'away_abbr': 'tulane',
                'away_name': 'Tulane',
                'away_rank': None,
                'away_score': 27,
                'boxscore': '2020-09-12-south-alabama',
                'home_abbr': 'south-alabama',
                'home_name': 'South Alabama',
                'home_rank': None,
                'home_score': 24,
                'losing_abbr': 'south-alabama',
                'losing_name': 'South Alabama',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'tulane',
                'winning_name': 'Tulane'},
                {'away_abbr': 'The Citadel',
                'away_name': 'The Citadel',
                'away_rank': None,
                'away_score': 6,
                'boxscore': '2020-09-12-south-florida',
                'home_abbr': 'south-florida',
                'home_name': 'South Florida',
                'home_rank': None,
                'home_score': 27,
                'losing_abbr': 'The Citadel',
                'losing_name': 'The Citadel',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'south-florida',
                'winning_name': 'South Florida'},
                {'away_abbr': 'texas-el-paso',
                'away_name': 'UTEP',
                'away_rank': None,
                'away_score': 3,
                'boxscore': '2020-09-12-texas',
                'home_abbr': 'texas',
                'home_name': 'Texas',
                'home_rank': 14,
                'home_score': 59,
                'losing_abbr': 'texas-el-paso',
                'losing_name': 'UTEP',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'texas',
                'winning_name': 'Texas'},
                {'away_abbr': 'texas-san-antonio',
                'away_name': 'UTSA',
                'away_rank': None,
                'away_score': 51,
                'boxscore': '2020-09-12-texas-state',
                'home_abbr': 'texas-state',
                'home_name': 'Texas State',
                'home_rank': None,
                'home_score': 48,
                'losing_abbr': 'texas-state',
                'losing_name': 'Texas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'texas-san-antonio',
                'winning_name': 'UTSA'},
                {'away_abbr': 'Houston Christian',
                'away_name': 'Houston Christian',
                'away_rank': None,
                'away_score': 33,
                'boxscore': '2020-09-12-texas-tech',
                'home_abbr': 'texas-tech',
                'home_name': 'Texas Tech',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'Houston Christian',
                'losing_name': 'Houston Christian',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'texas-tech',
                'winning_name': 'Texas Tech'},
                {'away_abbr': 'clemson',
                'away_name': 'Clemson',
                'away_rank': 1,
                'away_score': 37,
                'boxscore': '2020-09-12-wake-forest',
                'home_abbr': 'wake-forest',
                'home_name': 'Wake Forest',
                'home_rank': None,
                'home_score': 13,
                'losing_abbr': 'wake-forest',
                'losing_name': 'Wake Forest',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'clemson',
                'winning_name': 'Clemson'},
                {'away_abbr': 'Eastern Kentucky',
                'away_name': 'Eastern Kentucky',
                'away_rank': None,
                'away_score': 10,
                'boxscore': '2020-09-12-west-virginia',
                'home_abbr': 'west-virginia',
                'home_name': 'West Virginia',
                'home_rank': None,
                'home_score': 56,
                'losing_abbr': 'Eastern Kentucky',
                'losing_name': 'Eastern Kentucky',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'west-virginia',
                'winning_name': 'West Virginia'},
                {'away_abbr': 'alabama-birmingham',
                'away_name': 'UAB',
                'away_rank': None,
                'away_score': 14,
                'boxscore': '2020-09-10-miami-fl',
                'home_abbr': 'miami-fl',
                'home_name': 'Miami (FL)',
                'home_rank': None,
                'home_score': 31,
                'losing_abbr': 'alabama-birmingham',
                'losing_name': 'UAB',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'miami-fl',
                'winning_name': 'Miami (FL)'}
            ]
        }

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search(self, *args, **kwargs):
        result = Boxscores(datetime(2020, 9, 12)).games

        assert result == self.expected

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search_invalid_end(self, *args, **kwargs):
        result = Boxscores(datetime(2020, 9, 12), datetime(2020, 9, 11)).games

        assert result == self.expected

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search_multiple_days(self, *args, **kwargs):
        expected = {
            '9-12-2020': [
                {'away_abbr': 'charlotte',
                'away_name': 'Charlotte',
                'away_rank': None,
                'away_score': 20,
                'boxscore': '2020-09-12-appalachian-state',
                'home_abbr': 'appalachian-state',
                'home_name': 'Appalachian State',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'charlotte',
                'losing_name': 'Charlotte',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'appalachian-state',
                'winning_name': 'Appalachian State'},
                {'away_abbr': 'louisiana-monroe',
                'away_name': 'Louisiana-Monroe',
                'away_rank': None,
                'away_score': 7,
                'boxscore': '2020-09-12-army',
                'home_abbr': 'army',
                'home_name': 'Army',
                'home_rank': None,
                'home_score': 37,
                'losing_abbr': 'louisiana-monroe',
                'losing_name': 'Louisiana-Monroe',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'army',
                'winning_name': 'Army'},
                {'away_abbr': 'georgia-tech',
                'away_name': 'Georgia Tech',
                'away_rank': None,
                'away_score': 16,
                'boxscore': '2020-09-12-florida-state',
                'home_abbr': 'florida-state',
                'home_name': 'Florida State',
                'home_rank': None,
                'home_score': 13,
                'losing_abbr': 'florida-state',
                'losing_name': 'Florida State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'georgia-tech',
                'winning_name': 'Georgia Tech'},
                {'away_abbr': 'Campbell',
                'away_name': 'Campbell',
                'away_rank': None,
                'away_score': 26,
                'boxscore': '2020-09-12-georgia-southern',
                'home_abbr': 'georgia-southern',
                'home_name': 'Georgia Southern',
                'home_rank': None,
                'home_score': 27,
                'losing_abbr': 'Campbell',
                'losing_name': 'Campbell',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'georgia-southern',
                'winning_name': 'Georgia Southern'},
                {'away_abbr': 'louisiana-lafayette',
                'away_name': 'Louisiana',
                'away_rank': None,
                'away_score': 31,
                'boxscore': '2020-09-12-iowa-state',
                'home_abbr': 'iowa-state',
                'home_name': 'Iowa State',
                'home_rank': 23,
                'home_score': 14,
                'losing_abbr': 'iowa-state',
                'losing_name': 'Iowa State',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'louisiana-lafayette',
                'winning_name': 'Louisiana'},
                {'away_abbr': 'coastal-carolina',
                'away_name': 'Coastal Carolina',
                'away_rank': None,
                'away_score': 38,
                'boxscore': '2020-09-12-kansas',
                'home_abbr': 'kansas',
                'home_name': 'Kansas',
                'home_rank': None,
                'home_score': 23,
                'losing_abbr': 'kansas',
                'losing_name': 'Kansas',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'coastal-carolina',
                'winning_name': 'Coastal Carolina'},
                {'away_abbr': 'arkansas-state',
                'away_name': 'Arkansas State',
                'away_rank': None,
                'away_score': 35,
                'boxscore': '2020-09-12-kansas-state',
                'home_abbr': 'kansas-state',
                'home_name': 'Kansas State',
                'home_rank': None,
                'home_score': 31,
                'losing_abbr': 'kansas-state',
                'losing_name': 'Kansas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'arkansas-state',
                'winning_name': 'Arkansas State'},
                {'away_abbr': 'western-kentucky',
                'away_name': 'Western Kentucky',
                'away_rank': None,
                'away_score': 21,
                'boxscore': '2020-09-12-louisville',
                'home_abbr': 'louisville',
                'home_name': 'Louisville',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'western-kentucky',
                'losing_name': 'Western Kentucky',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'louisville',
                'winning_name': 'Louisville'},
                {'away_abbr': 'syracuse',
                'away_name': 'Syracuse',
                'away_rank': None,
                'away_score': 6,
                'boxscore': '2020-09-12-north-carolina',
                'home_abbr': 'north-carolina',
                'home_name': 'North Carolina',
                'home_rank': 18,
                'home_score': 31,
                'losing_abbr': 'syracuse',
                'losing_name': 'Syracuse',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'north-carolina',
                'winning_name': 'North Carolina'},
                {'away_abbr': 'duke',
                'away_name': 'Duke',
                'away_rank': None,
                'away_score': 13,
                'boxscore': '2020-09-12-notre-dame',
                'home_abbr': 'notre-dame',
                'home_name': 'Notre Dame',
                'home_rank': 10,
                'home_score': 27,
                'losing_abbr': 'duke',
                'losing_name': 'Duke',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'notre-dame',
                'winning_name': 'Notre Dame'},
                {'away_abbr': 'Missouri State',
                'away_name': 'Missouri State',
                'away_rank': None,
                'away_score': 0,
                'boxscore': '2020-09-12-oklahoma',
                'home_abbr': 'oklahoma',
                'home_name': 'Oklahoma',
                'home_rank': 5,
                'home_score': 48,
                'losing_abbr': None,
                'losing_name': None,
                'non_di': True,
                'top_25': True,
                'winning_abbr': None,
                'winning_name': None},
                {'away_abbr': 'Austin Peay',
                'away_name': 'Austin Peay',
                'away_rank': None,
                'away_score': 0,
                'boxscore': '2020-09-12-pittsburgh',
                'home_abbr': 'pittsburgh',
                'home_name': 'Pitt',
                'home_rank': None,
                'home_score': 55,
                'losing_abbr': None,
                'losing_name': None,
                'non_di': True,
                'top_25': False,
                'winning_abbr': None,
                'winning_name': None},
                {'away_abbr': 'tulane',
                'away_name': 'Tulane',
                'away_rank': None,
                'away_score': 27,
                'boxscore': '2020-09-12-south-alabama',
                'home_abbr': 'south-alabama',
                'home_name': 'South Alabama',
                'home_rank': None,
                'home_score': 24,
                'losing_abbr': 'south-alabama',
                'losing_name': 'South Alabama',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'tulane',
                'winning_name': 'Tulane'},
                {'away_abbr': 'The Citadel',
                'away_name': 'The Citadel',
                'away_rank': None,
                'away_score': 6,
                'boxscore': '2020-09-12-south-florida',
                'home_abbr': 'south-florida',
                'home_name': 'South Florida',
                'home_rank': None,
                'home_score': 27,
                'losing_abbr': 'The Citadel',
                'losing_name': 'The Citadel',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'south-florida',
                'winning_name': 'South Florida'},
                {'away_abbr': 'texas-el-paso',
                'away_name': 'UTEP',
                'away_rank': None,
                'away_score': 3,
                'boxscore': '2020-09-12-texas',
                'home_abbr': 'texas',
                'home_name': 'Texas',
                'home_rank': 14,
                'home_score': 59,
                'losing_abbr': 'texas-el-paso',
                'losing_name': 'UTEP',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'texas',
                'winning_name': 'Texas'},
                {'away_abbr': 'texas-san-antonio',
                'away_name': 'UTSA',
                'away_rank': None,
                'away_score': 51,
                'boxscore': '2020-09-12-texas-state',
                'home_abbr': 'texas-state',
                'home_name': 'Texas State',
                'home_rank': None,
                'home_score': 48,
                'losing_abbr': 'texas-state',
                'losing_name': 'Texas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'texas-san-antonio',
                'winning_name': 'UTSA'},
                {'away_abbr': 'Houston Christian',
                'away_name': 'Houston Christian',
                'away_rank': None,
                'away_score': 33,
                'boxscore': '2020-09-12-texas-tech',
                'home_abbr': 'texas-tech',
                'home_name': 'Texas Tech',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'Houston Christian',
                'losing_name': 'Houston Christian',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'texas-tech',
                'winning_name': 'Texas Tech'},
                {'away_abbr': 'clemson',
                'away_name': 'Clemson',
                'away_rank': 1,
                'away_score': 37,
                'boxscore': '2020-09-12-wake-forest',
                'home_abbr': 'wake-forest',
                'home_name': 'Wake Forest',
                'home_rank': None,
                'home_score': 13,
                'losing_abbr': 'wake-forest',
                'losing_name': 'Wake Forest',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'clemson',
                'winning_name': 'Clemson'},
                {'away_abbr': 'Eastern Kentucky',
                'away_name': 'Eastern Kentucky',
                'away_rank': None,
                'away_score': 10,
                'boxscore': '2020-09-12-west-virginia',
                'home_abbr': 'west-virginia',
                'home_name': 'West Virginia',
                'home_rank': None,
                'home_score': 56,
                'losing_abbr': 'Eastern Kentucky',
                'losing_name': 'Eastern Kentucky',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'west-virginia',
                'winning_name': 'West Virginia'},
                {'away_abbr': 'alabama-birmingham',
                'away_name': 'UAB',
                'away_rank': None,
                'away_score': 14,
                'boxscore': '2020-09-10-miami-fl',
                'home_abbr': 'miami-fl',
                'home_name': 'Miami (FL)',
                'home_rank': None,
                'home_score': 31,
                'losing_abbr': 'alabama-birmingham',
                'losing_name': 'UAB',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'miami-fl',
                'winning_name': 'Miami (FL)'}],
            '9-13-2020': [
                {'away_abbr': 'charlotte',
                'away_name': 'Charlotte',
                'away_rank': None,
                'away_score': 20,
                'boxscore': '2020-09-12-appalachian-state',
                'home_abbr': 'appalachian-state',
                'home_name': 'Appalachian State',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'charlotte',
                'losing_name': 'Charlotte',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'appalachian-state',
                'winning_name': 'Appalachian State'},
               {'away_abbr': 'louisiana-monroe',
                'away_name': 'Louisiana-Monroe',
                'away_rank': None,
                'away_score': 7,
                'boxscore': '2020-09-12-army',
                'home_abbr': 'army',
                'home_name': 'Army',
                'home_rank': None,
                'home_score': 37,
                'losing_abbr': 'louisiana-monroe',
                'losing_name': 'Louisiana-Monroe',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'army',
                'winning_name': 'Army'},
               {'away_abbr': 'georgia-tech',
                'away_name': 'Georgia Tech',
                'away_rank': None,
                'away_score': 16,
                'boxscore': '2020-09-12-florida-state',
                'home_abbr': 'florida-state',
                'home_name': 'Florida State',
                'home_rank': None,
                'home_score': 13,
                'losing_abbr': 'florida-state',
                'losing_name': 'Florida State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'georgia-tech',
                'winning_name': 'Georgia Tech'},
               {'away_abbr': 'Campbell',
                'away_name': 'Campbell',
                'away_rank': None,
                'away_score': 26,
                'boxscore': '2020-09-12-georgia-southern',
                'home_abbr': 'georgia-southern',
                'home_name': 'Georgia Southern',
                'home_rank': None,
                'home_score': 27,
                'losing_abbr': 'Campbell',
                'losing_name': 'Campbell',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'georgia-southern',
                'winning_name': 'Georgia Southern'},
               {'away_abbr': 'louisiana-lafayette',
                'away_name': 'Louisiana',
                'away_rank': None,
                'away_score': 31,
                'boxscore': '2020-09-12-iowa-state',
                'home_abbr': 'iowa-state',
                'home_name': 'Iowa State',
                'home_rank': 23,
                'home_score': 14,
                'losing_abbr': 'iowa-state',
                'losing_name': 'Iowa State',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'louisiana-lafayette',
                'winning_name': 'Louisiana'},
               {'away_abbr': 'coastal-carolina',
                'away_name': 'Coastal Carolina',
                'away_rank': None,
                'away_score': 38,
                'boxscore': '2020-09-12-kansas',
                'home_abbr': 'kansas',
                'home_name': 'Kansas',
                'home_rank': None,
                'home_score': 23,
                'losing_abbr': 'kansas',
                'losing_name': 'Kansas',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'coastal-carolina',
                'winning_name': 'Coastal Carolina'},
               {'away_abbr': 'arkansas-state',
                'away_name': 'Arkansas State',
                'away_rank': None,
                'away_score': 35,
                'boxscore': '2020-09-12-kansas-state',
                'home_abbr': 'kansas-state',
                'home_name': 'Kansas State',
                'home_rank': None,
                'home_score': 31,
                'losing_abbr': 'kansas-state',
                'losing_name': 'Kansas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'arkansas-state',
                'winning_name': 'Arkansas State'},
               {'away_abbr': 'western-kentucky',
                'away_name': 'Western Kentucky',
                'away_rank': None,
                'away_score': 21,
                'boxscore': '2020-09-12-louisville',
                'home_abbr': 'louisville',
                'home_name': 'Louisville',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'western-kentucky',
                'losing_name': 'Western Kentucky',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'louisville',
                'winning_name': 'Louisville'},
               {'away_abbr': 'syracuse',
                'away_name': 'Syracuse',
                'away_rank': None,
                'away_score': 6,
                'boxscore': '2020-09-12-north-carolina',
                'home_abbr': 'north-carolina',
                'home_name': 'North Carolina',
                'home_rank': 18,
                'home_score': 31,
                'losing_abbr': 'syracuse',
                'losing_name': 'Syracuse',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'north-carolina',
                'winning_name': 'North Carolina'},
               {'away_abbr': 'duke',
                'away_name': 'Duke',
                'away_rank': None,
                'away_score': 13,
                'boxscore': '2020-09-12-notre-dame',
                'home_abbr': 'notre-dame',
                'home_name': 'Notre Dame',
                'home_rank': 10,
                'home_score': 27,
                'losing_abbr': 'duke',
                'losing_name': 'Duke',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'notre-dame',
                'winning_name': 'Notre Dame'},
               {'away_abbr': 'Missouri State',
                'away_name': 'Missouri State',
                'away_rank': None,
                'away_score': 0,
                'boxscore': '2020-09-12-oklahoma',
                'home_abbr': 'oklahoma',
                'home_name': 'Oklahoma',
                'home_rank': 5,
                'home_score': 48,
                'losing_abbr': None,
                'losing_name': None,
                'non_di': True,
                'top_25': True,
                'winning_abbr': None,
                'winning_name': None},
               {'away_abbr': 'Austin Peay',
                'away_name': 'Austin Peay',
                'away_rank': None,
                'away_score': 0,
                'boxscore': '2020-09-12-pittsburgh',
                'home_abbr': 'pittsburgh',
                'home_name': 'Pitt',
                'home_rank': None,
                'home_score': 55,
                'losing_abbr': None,
                'losing_name': None,
                'non_di': True,
                'top_25': False,
                'winning_abbr': None,
                'winning_name': None},
               {'away_abbr': 'tulane',
                'away_name': 'Tulane',
                'away_rank': None,
                'away_score': 27,
                'boxscore': '2020-09-12-south-alabama',
                'home_abbr': 'south-alabama',
                'home_name': 'South Alabama',
                'home_rank': None,
                'home_score': 24,
                'losing_abbr': 'south-alabama',
                'losing_name': 'South Alabama',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'tulane',
                'winning_name': 'Tulane'},
               {'away_abbr': 'The Citadel',
                'away_name': 'The Citadel',
                'away_rank': None,
                'away_score': 6,
                'boxscore': '2020-09-12-south-florida',
                'home_abbr': 'south-florida',
                'home_name': 'South Florida',
                'home_rank': None,
                'home_score': 27,
                'losing_abbr': 'The Citadel',
                'losing_name': 'The Citadel',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'south-florida',
                'winning_name': 'South Florida'},
               {'away_abbr': 'texas-el-paso',
                'away_name': 'UTEP',
                'away_rank': None,
                'away_score': 3,
                'boxscore': '2020-09-12-texas',
                'home_abbr': 'texas',
                'home_name': 'Texas',
                'home_rank': 14,
                'home_score': 59,
                'losing_abbr': 'texas-el-paso',
                'losing_name': 'UTEP',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'texas',
                'winning_name': 'Texas'},
               {'away_abbr': 'texas-san-antonio',
                'away_name': 'UTSA',
                'away_rank': None,
                'away_score': 51,
                'boxscore': '2020-09-12-texas-state',
                'home_abbr': 'texas-state',
                'home_name': 'Texas State',
                'home_rank': None,
                'home_score': 48,
                'losing_abbr': 'texas-state',
                'losing_name': 'Texas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'texas-san-antonio',
                'winning_name': 'UTSA'},
               {'away_abbr': 'Houston Christian',
                'away_name': 'Houston Christian',
                'away_rank': None,
                'away_score': 33,
                'boxscore': '2020-09-12-texas-tech',
                'home_abbr': 'texas-tech',
                'home_name': 'Texas Tech',
                'home_rank': None,
                'home_score': 35,
                'losing_abbr': 'Houston Christian',
                'losing_name': 'Houston Christian',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'texas-tech',
                'winning_name': 'Texas Tech'},
               {'away_abbr': 'clemson',
                'away_name': 'Clemson',
                'away_rank': 1,
                'away_score': 37,
                'boxscore': '2020-09-12-wake-forest',
                'home_abbr': 'wake-forest',
                'home_name': 'Wake Forest',
                'home_rank': None,
                'home_score': 13,
                'losing_abbr': 'wake-forest',
                'losing_name': 'Wake Forest',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'clemson',
                'winning_name': 'Clemson'},
               {'away_abbr': 'Eastern Kentucky',
                'away_name': 'Eastern Kentucky',
                'away_rank': None,
                'away_score': 10,
                'boxscore': '2020-09-12-west-virginia',
                'home_abbr': 'west-virginia',
                'home_name': 'West Virginia',
                'home_rank': None,
                'home_score': 56,
                'losing_abbr': 'Eastern Kentucky',
                'losing_name': 'Eastern Kentucky',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'west-virginia',
                'winning_name': 'West Virginia'},
               {'away_abbr': 'alabama-birmingham',
                'away_name': 'UAB',
                'away_rank': None,
                'away_score': 14,
                'boxscore': '2020-09-10-miami-fl',
                'home_abbr': 'miami-fl',
                'home_name': 'Miami (FL)',
                'home_rank': None,
                'home_score': 31,
                'losing_abbr': 'alabama-birmingham',
                'losing_name': 'UAB',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'miami-fl',
                'winning_name': 'Miami (FL)'}
            ]
        }
        result = Boxscores(datetime(2020, 9, 12), datetime(2020, 9, 13)).games
        from pprint import pprint
        pprint(result)
        assert result == expected

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search_string_representation(self, *args, **kwargs):
        result = Boxscores(datetime(2020, 9, 12))

        assert result.__repr__() == 'NCAAF games for 9-12-2020'
