import mock
import os
import pandas as pd
from datetime import datetime
from flexmock import flexmock
from sportsipy import utils
from sportsipy.constants import HOME
from sportsipy.ncaab.constants import BOXSCORES_URL, SCHEDULE_URL
from sportsipy.ncaab.boxscore import Boxscore, Boxscores
from pyquery import PyQuery as pq
from ..utils import read_file


MONTH = 1
YEAR = 2020

BOXSCORE = '2020-01-22-19-louisville'


def mock_pyquery(url):
    if url == BOXSCORES_URL % (MONTH, 5, YEAR):
        return read_file('boxscores-1-5-2020.html', 'ncaab', 'boxscore')
    if url == BOXSCORES_URL % (MONTH, 6, YEAR):
        return read_file('boxscores-1-6-2020.html', 'ncaab', 'boxscore')
    boxscore = read_file('%s.html' % BOXSCORE, 'ncaab', 'boxscore')
    return boxscore


class MockDateTime:
    def __init__(self, year, month):
        self.year = year
        self.month = month


class TestNCAABBoxscore:
    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def setup_method(self, *args, **kwargs):
        self.results = {
            'date': 'January 22, 2020',
            'location': 'KFC Yum! Center, Louisville, Kentucky',
            'winner': HOME,
            'winning_name': 'Louisville',
            'winning_abbr': 'LOUISVILLE',
            'losing_name': 'Georgia Tech',
            'losing_abbr': 'GEORGIA-TECH',
            'pace': 66.2,
            'away_ranking': None,
            'away_win_percentage': .421,
            'away_wins': 8,
            'away_losses': 11,
            'away_minutes_played': 200,
            'away_field_goals': 22,
            'away_field_goal_attempts': 48,
            'away_field_goal_percentage': .458,
            'away_two_point_field_goals': 17,
            'away_two_point_field_goal_attempts': 31,
            'away_two_point_field_goal_percentage': .548,
            'away_three_point_field_goals': 5,
            'away_three_point_field_goal_attempts': 17,
            'away_three_point_field_goal_percentage': .294,
            'away_free_throws': 15,
            'away_free_throw_attempts': 20,
            'away_free_throw_percentage': .750,
            'away_offensive_rebounds': 7,
            'away_defensive_rebounds': 23,
            'away_total_rebounds': 30,
            'away_assists': 11,
            'away_steals': 4,
            'away_blocks': 4,
            'away_turnovers': 16,
            'away_personal_fouls': 18,
            'away_points': 64,
            'away_true_shooting_percentage': .557,
            'away_effective_field_goal_percentage': .510,
            'away_three_point_attempt_rate': .354,
            'away_free_throw_attempt_rate': .417,
            'away_offensive_rebound_percentage': 28.0,
            'away_defensive_rebound_percentage': 63.9,
            'away_total_rebound_percentage': 49.2,
            'away_assist_percentage': 50.0,
            'away_steal_percentage': 6.1,
            'away_block_percentage': 10.5,
            'away_turnover_percentage': 22.0,
            'away_offensive_rating': 97.0,
            'away_defensive_rating': 103.0,
            'home_ranking': 6,
            'home_win_percentage': .842,
            'home_wins': 16,
            'home_losses': 3,
            'home_minutes_played': 200,
            'home_field_goals': 24,
            'home_field_goal_attempts': 58,
            'home_field_goal_percentage': .414,
            'home_two_point_field_goals': 18,
            'home_two_point_field_goal_attempts': 38,
            'home_two_point_field_goal_percentage': .474,
            'home_three_point_field_goals': 6,
            'home_three_point_field_goal_attempts': 20,
            'home_three_point_field_goal_percentage': .300,
            'home_free_throws': 14,
            'home_free_throw_attempts': 23,
            'home_free_throw_percentage': .609,
            'home_offensive_rebounds': 13,
            'home_defensive_rebounds': 18,
            'home_total_rebounds': 31,
            'home_assists': 12,
            'home_steals': 9,
            'home_blocks': 3,
            'home_turnovers': 10,
            'home_personal_fouls': 17,
            'home_points': 68,
            'home_true_shooting_percentage': .493,
            'home_effective_field_goal_percentage': .466,
            'home_three_point_attempt_rate': .345,
            'home_free_throw_attempt_rate': .397,
            'home_offensive_rebound_percentage': 36.1,
            'home_defensive_rebound_percentage': 72.0,
            'home_total_rebound_percentage': 50.8,
            'home_assist_percentage': 50.0,
            'home_steal_percentage': 13.6,
            'home_block_percentage': 9.7,
            'home_turnover_percentage': 12.8,
            'home_offensive_rating': 103.0,
            'home_defensive_rating': 97.0
        }
        flexmock(utils) \
            .should_receive('_todays_date') \
            .and_return(MockDateTime(YEAR, MONTH))

        self.boxscore = Boxscore('2020-01-22-19-louisville')

    def test_ncaab_boxscore_returns_requested_boxscore(self):
        for attribute, value in self.results.items():
            assert getattr(self.boxscore, attribute) == value
        assert getattr(self.boxscore, 'summary') == {
            # Box score is not parsed correctly
            'away': [],
            'home': []
        }

    def test_invalid_url_yields_empty_class(self):
        flexmock(Boxscore) \
            .should_receive('_retrieve_html_page') \
            .and_return(None)

        boxscore = Boxscore(BOXSCORE)

        for key, value in boxscore.__dict__.items():
            if key == '_uri':
                continue
            assert value is None

    def test_ncaab_boxscore_dataframe_returns_dataframe_of_all_values(self):
        df = pd.DataFrame([self.results], index=[BOXSCORE])

        # Pandas doesn't natively allow comparisons of DataFrames.
        # Concatenating the two DataFrames (the one generated during the test
        # and the expected one above) and dropping duplicate rows leaves only
        # the rows that are unique between the two frames. This allows a quick
        # check of the DataFrame to see if it is empty - if so, all rows are
        # duplicates, and they are equal.
        frames = [df, self.boxscore.dataframe]
        df1 = pd.concat(frames).drop_duplicates(keep=False)

        assert df1.empty

    def test_ncaab_boxscore_players(self):
        boxscore = self.boxscore

        assert len(boxscore.home_players) == 10
        assert len(boxscore.away_players) == 7

        for player in boxscore.home_players:
            assert not player.dataframe.empty
        for player in boxscore.away_players:
            assert not player.dataframe.empty

    def test_ncaab_boxscore_string_representation(self):
        expected = ('Boxscore for Georgia Tech '
                    'at Louisville (January 22, 2020)')

        assert self.boxscore.__repr__() == expected


class TestNCAABBoxscores:
    def setup_method(self):
        self.expected = {
            '1-5-2020': [
                {'away_abbr': 'michigan',
                'away_name': 'Michigan',
                'away_rank': 12,
                'away_score': 69,
                'boxscore': '2020-01-05-13-michigan-state',
                'home_abbr': 'michigan-state',
                'home_name': 'Michigan State',
                'home_rank': 14,
                'home_score': 87,
                'losing_abbr': 'michigan',
                'losing_name': 'Michigan',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'michigan-state',
                'winning_name': 'Michigan State'},
                {'away_abbr': 'dayton',
                'away_name': 'Dayton',
                'away_rank': 20,
                'away_score': 80,
                'boxscore': '2020-01-05-13-saint-josephs',
                'home_abbr': 'saint-josephs',
                'home_name': "St. Joseph's",
                'home_rank': None,
                'home_score': 67,
                'losing_abbr': 'saint-josephs',
                'losing_name': "St. Joseph's",
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'dayton',
                'winning_name': 'Dayton'},
                {'away_abbr': 'virginia-commonwealth',
                'away_name': 'VCU',
                'away_rank': None,
                'away_score': 72,
                'boxscore': '2020-01-05-12-george-mason',
                'home_abbr': 'george-mason',
                'home_name': 'George Mason',
                'home_rank': None,
                'home_score': 59,
                'losing_abbr': 'george-mason',
                'losing_name': 'George Mason',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'virginia-commonwealth',
                'winning_name': 'VCU'},
                {'away_abbr': 'navy',
                'away_name': 'Navy',
                'away_rank': None,
                'away_score': 61,
                'boxscore': '2020-01-05-12-holy-cross',
                'home_abbr': 'holy-cross',
                'home_name': 'Holy Cross',
                'home_rank': None,
                'home_score': 63,
                'losing_abbr': 'navy',
                'losing_name': 'Navy',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'holy-cross',
                'winning_name': 'Holy Cross'},
                {'away_abbr': 'richmond',
                'away_name': 'Richmond',
                'away_rank': None,
                'away_score': 69,
                'boxscore': '2020-01-05-12-rhode-island',
                'home_abbr': 'rhode-island',
                'home_name': 'Rhode Island',
                'home_rank': None,
                'home_score': 61,
                'losing_abbr': 'rhode-island',
                'losing_name': 'Rhode Island',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'richmond',
                'winning_name': 'Richmond'},
                {'away_abbr': 'wright-state',
                'away_name': 'Wright State',
                'away_rank': None,
                'away_score': 70,
                'boxscore': '2020-01-05-13-detroit-mercy',
                'home_abbr': 'detroit-mercy',
                'home_name': 'Detroit',
                'home_rank': None,
                'home_score': 69,
                'losing_abbr': 'detroit-mercy',
                'losing_name': 'Detroit',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'wright-state',
                'winning_name': 'Wright State'},
                {'away_abbr': 'stony-brook',
                'away_name': 'Stony Brook',
                'away_rank': None,
                'away_score': 73,
                'boxscore': '2020-01-05-13-maine',
                'home_abbr': 'maine',
                'home_name': 'Maine',
                'home_rank': None,
                'home_score': 52,
                'losing_abbr': 'maine',
                'losing_name': 'Maine',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'stony-brook',
                'winning_name': 'Stony Brook'},
                {'away_abbr': 'manhattan',
                'away_name': 'Manhattan',
                'away_rank': None,
                'away_score': 67,
                'boxscore': '2020-01-05-13-niagara',
                'home_abbr': 'niagara',
                'home_name': 'Niagara',
                'home_rank': None,
                'home_score': 62,
                'losing_abbr': 'niagara',
                'losing_name': 'Niagara',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'manhattan',
                'winning_name': 'Manhattan'},
                {'away_abbr': 'fairfield',
                'away_name': 'Fairfield',
                'away_rank': None,
                'away_score': 46,
                'boxscore': '2020-01-05-14-canisius',
                'home_abbr': 'canisius',
                'home_name': 'Canisius',
                'home_rank': None,
                'home_score': 42,
                'losing_abbr': 'canisius',
                'losing_name': 'Canisius',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'fairfield',
                'winning_name': 'Fairfield'},
                {'away_abbr': 'davidson',
                'away_name': 'Davidson',
                'away_rank': None,
                'away_score': 64,
                'boxscore': '2020-01-05-14-duquesne',
                'home_abbr': 'duquesne',
                'home_name': 'Duquesne',
                'home_rank': None,
                'home_score': 71,
                'losing_abbr': 'davidson',
                'losing_name': 'Davidson',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'duquesne',
                'winning_name': 'Duquesne'},
                {'away_abbr': 'la-salle',
                'away_name': 'La Salle',
                'away_rank': None,
                'away_score': 66,
                'boxscore': '2020-01-05-14-fordham',
                'home_abbr': 'fordham',
                'home_name': 'Fordham',
                'home_rank': None,
                'home_score': 60,
                'losing_abbr': 'fordham',
                'losing_name': 'Fordham',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'la-salle',
                'winning_name': 'La Salle'},
                {'away_abbr': 'iupui',
                'away_name': 'IUPUI',
                'away_rank': None,
                'away_score': 93,
                'boxscore': '2020-01-05-14-green-bay',
                'home_abbr': 'green-bay',
                'home_name': 'Green Bay',
                'home_rank': None,
                'home_score': 78,
                'losing_abbr': 'green-bay',
                'losing_name': 'Green Bay',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'iupui',
                'winning_name': 'IUPUI'},
                {'away_abbr': 'bucknell',
                'away_name': 'Bucknell',
                'away_rank': None,
                'away_score': 78,
                'boxscore': '2020-01-05-14-lafayette',
                'home_abbr': 'lafayette',
                'home_name': 'Lafayette',
                'home_rank': None,
                'home_score': 66,
                'losing_abbr': 'lafayette',
                'losing_name': 'Lafayette',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'bucknell',
                'winning_name': 'Bucknell'},
                {'away_abbr': 'loyola-md',
                'away_name': 'Loyola (MD)',
                'away_rank': None,
                'away_score': 71,
                'boxscore': '2020-01-05-14-lehigh',
                'home_abbr': 'lehigh',
                'home_name': 'Lehigh',
                'home_rank': None,
                'home_score': 78,
                'losing_abbr': 'loyola-md',
                'losing_name': 'Loyola (MD)',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'lehigh',
                'winning_name': 'Lehigh'},
                {'away_abbr': 'illinois-chicago',
                'away_name': 'UIC',
                'away_rank': None,
                'away_score': 62,
                'boxscore': '2020-01-05-14-milwaukee',
                'home_abbr': 'milwaukee',
                'home_name': 'Milwaukee',
                'home_rank': None,
                'home_score': 64,
                'losing_abbr': 'illinois-chicago',
                'losing_name': 'UIC',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'milwaukee',
                'winning_name': 'Milwaukee'},
                {'away_abbr': 'iona',
                'away_name': 'Iona',
                'away_rank': None,
                'away_score': 61,
                'boxscore': '2020-01-05-14-monmouth',
                'home_abbr': 'monmouth',
                'home_name': 'Monmouth',
                'home_rank': None,
                'home_score': 73,
                'losing_abbr': 'iona',
                'losing_name': 'Iona',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'monmouth',
                'winning_name': 'Monmouth'},
                {'away_abbr': 'siena',
                'away_name': 'Siena',
                'away_rank': None,
                'away_score': 77,
                'boxscore': '2020-01-05-14-rider',
                'home_abbr': 'rider',
                'home_name': 'Rider',
                'home_rank': None,
                'home_score': 85,
                'losing_abbr': 'siena',
                'losing_name': 'Siena',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'rider',
                'winning_name': 'Rider'},
                {'away_abbr': 'marist',
                'away_name': 'Marist',
                'away_rank': None,
                'away_score': 40,
                'boxscore': '2020-01-05-14-saint-peters',
                'home_abbr': 'saint-peters',
                'home_name': "St. Peter's",
                'home_rank': None,
                'home_score': 66,
                'losing_abbr': 'marist',
                'losing_name': 'Marist',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'saint-peters',
                'winning_name': "St. Peter's"},
                {'away_abbr': 'boston-university',
                'away_name': 'Boston University',
                'away_rank': None,
                'away_score': 63,
                'boxscore': '2020-01-05-15-american',
                'home_abbr': 'american',
                'home_name': 'American',
                'home_rank': None,
                'home_score': 67,
                'losing_abbr': 'boston-university',
                'losing_name': 'Boston University',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'american',
                'winning_name': 'American'},
                {'away_abbr': 'Northland',
                'away_name': 'Northland',
                'away_rank': None,
                'away_score': 43,
                'boxscore': '2020-01-05-15-north-dakota-state',
                'home_abbr': 'north-dakota-state',
                'home_name': 'North Dakota State',
                'home_rank': None,
                'home_score': 97,
                'losing_abbr': 'Northland',
                'losing_name': 'Northland',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'north-dakota-state',
                'winning_name': 'North Dakota State'},
                {'away_abbr': 'northern-kentucky',
                'away_name': 'Northern Kentucky',
                'away_rank': None,
                'away_score': 75,
                'boxscore': '2020-01-05-15-oakland',
                'home_abbr': 'oakland',
                'home_name': 'Oakland',
                'home_rank': None,
                'home_score': 64,
                'losing_abbr': 'oakland',
                'losing_name': 'Oakland',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'northern-kentucky',
                'winning_name': 'Northern Kentucky'},
                {'away_abbr': 'st-bonaventure',
                'away_name': 'St. Bonaventure',
                'away_rank': None,
                'away_score': 71,
                'boxscore': '2020-01-05-16-george-washington',
                'home_abbr': 'george-washington',
                'home_name': 'George Washington',
                'home_rank': None,
                'home_score': 66,
                'losing_abbr': 'george-washington',
                'losing_name': 'George Washington',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'st-bonaventure',
                'winning_name': 'St. Bonaventure'},
                {'away_abbr': 'massachusetts',
                'away_name': 'UMass',
                'away_rank': None,
                'away_score': 80,
                'boxscore': '2020-01-05-16-saint-louis',
                'home_abbr': 'saint-louis',
                'home_name': 'Saint Louis',
                'home_rank': None,
                'home_score': 83,
                'losing_abbr': 'massachusetts',
                'losing_name': 'UMass',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'saint-louis',
                'winning_name': 'Saint Louis'},
                {'away_abbr': 'denver',
                'away_name': 'Denver',
                'away_rank': None,
                'away_score': 78,
                'boxscore': '2020-01-05-16-south-dakota',
                'home_abbr': 'south-dakota',
                'home_name': 'South Dakota',
                'home_rank': None,
                'home_score': 80,
                'losing_abbr': 'denver',
                'losing_name': 'Denver',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'south-dakota',
                'winning_name': 'South Dakota'},
                {'away_abbr': 'st-johns-ny',
                'away_name': "St. John's (NY)",
                'away_rank': None,
                'away_score': 67,
                'boxscore': '2020-01-05-16-xavier',
                'home_abbr': 'xavier',
                'home_name': 'Xavier',
                'home_rank': None,
                'home_score': 75,
                'losing_abbr': 'st-johns-ny',
                'losing_name': "St. John's (NY)",
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'xavier',
                'winning_name': 'Xavier'},
                {'away_abbr': 'ipfw',
                'away_name': 'Purdue-Fort Wayne',
                'away_rank': None,
                'away_score': 69,
                'boxscore': '2020-01-05-17-north-dakota',
                'home_abbr': 'north-dakota',
                'home_name': 'North Dakota',
                'home_rank': None,
                'home_score': 83,
                'losing_abbr': 'ipfw',
                'losing_name': 'Purdue-Fort Wayne',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'north-dakota',
                'winning_name': 'North Dakota'},
                {'away_abbr': 'houston-baptist',
                'away_name': 'Houston Christian',
                'away_rank': None,
                'away_score': 79,
                'boxscore': '2020-01-05-17-northwestern-state',
                'home_abbr': 'northwestern-state',
                'home_name': 'Northwestern State',
                'home_rank': None,
                'home_score': 106,
                'losing_abbr': 'houston-baptist',
                'losing_name': 'Houston Christian',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'northwestern-state',
                'winning_name': 'Northwestern State'},
                {'away_abbr': 'oregon-state',
                'away_name': 'Oregon State',
                'away_rank': None,
                'away_score': 76,
                'boxscore': '2020-01-05-18-colorado',
                'home_abbr': 'colorado',
                'home_name': 'Colorado',
                'home_rank': None,
                'home_score': 68,
                'losing_abbr': 'colorado',
                'losing_name': 'Colorado',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'oregon-state',
                'winning_name': 'Oregon State'},
                {'away_abbr': 'northwestern',
                'away_name': 'Northwestern',
                'away_rank': None,
                'away_score': 68,
                'boxscore': '2020-01-05-19-minnesota',
                'home_abbr': 'minnesota',
                'home_name': 'Minnesota',
                'home_rank': None,
                'home_score': 77,
                'losing_abbr': 'northwestern',
                'losing_name': 'Northwestern',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'minnesota',
                'winning_name': 'Minnesota'},
                {'away_abbr': 'purdue',
                'away_name': 'Purdue',
                'away_rank': None,
                'away_score': 37,
                'boxscore': '2020-01-05-20-illinois',
                'home_abbr': 'illinois',
                'home_name': 'Illinois',
                'home_rank': None,
                'home_score': 63,
                'losing_abbr': 'purdue',
                'losing_name': 'Purdue',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'illinois',
                'winning_name': 'Illinois'},
                {'away_abbr': 'southern-california',
                'away_name': 'USC',
                'away_rank': None,
                'away_score': 40,
                'boxscore': '2020-01-05-22-washington',
                'home_abbr': 'washington',
                'home_name': 'Washington',
                'home_rank': None,
                'home_score': 72,
                'losing_abbr': 'southern-california',
                'losing_name': 'USC',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'washington',
                'winning_name': 'Washington'}]}

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search(self, *args, **kwargs):
        result = Boxscores(datetime(2020, 1, 5)).games

        assert result == self.expected

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search_invalid_end(self, *args, **kwargs):
        result = Boxscores(datetime(2020, 1, 5),
                           datetime(2020, 1, 4)).games

        assert result == self.expected

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search_multiple_days(self, *args, **kwargs):
        expected = {
            '1-5-2020': [
                {'away_abbr': 'michigan',
                'away_name': 'Michigan',
                'away_rank': 12,
                'away_score': 69,
                'boxscore': '2020-01-05-13-michigan-state',
                'home_abbr': 'michigan-state',
                'home_name': 'Michigan State',
                'home_rank': 14,
                'home_score': 87,
                'losing_abbr': 'michigan',
                'losing_name': 'Michigan',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'michigan-state',
                'winning_name': 'Michigan State'},
                {'away_abbr': 'dayton',
                'away_name': 'Dayton',
                'away_rank': 20,
                'away_score': 80,
                'boxscore': '2020-01-05-13-saint-josephs',
                'home_abbr': 'saint-josephs',
                'home_name': "St. Joseph's",
                'home_rank': None,
                'home_score': 67,
                'losing_abbr': 'saint-josephs',
                'losing_name': "St. Joseph's",
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'dayton',
                'winning_name': 'Dayton'},
                {'away_abbr': 'virginia-commonwealth',
                'away_name': 'VCU',
                'away_rank': None,
                'away_score': 72,
                'boxscore': '2020-01-05-12-george-mason',
                'home_abbr': 'george-mason',
                'home_name': 'George Mason',
                'home_rank': None,
                'home_score': 59,
                'losing_abbr': 'george-mason',
                'losing_name': 'George Mason',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'virginia-commonwealth',
                'winning_name': 'VCU'},
                {'away_abbr': 'navy',
                'away_name': 'Navy',
                'away_rank': None,
                'away_score': 61,
                'boxscore': '2020-01-05-12-holy-cross',
                'home_abbr': 'holy-cross',
                'home_name': 'Holy Cross',
                'home_rank': None,
                'home_score': 63,
                'losing_abbr': 'navy',
                'losing_name': 'Navy',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'holy-cross',
                'winning_name': 'Holy Cross'},
                {'away_abbr': 'richmond',
                'away_name': 'Richmond',
                'away_rank': None,
                'away_score': 69,
                'boxscore': '2020-01-05-12-rhode-island',
                'home_abbr': 'rhode-island',
                'home_name': 'Rhode Island',
                'home_rank': None,
                'home_score': 61,
                'losing_abbr': 'rhode-island',
                'losing_name': 'Rhode Island',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'richmond',
                'winning_name': 'Richmond'},
                {'away_abbr': 'wright-state',
                'away_name': 'Wright State',
                'away_rank': None,
                'away_score': 70,
                'boxscore': '2020-01-05-13-detroit-mercy',
                'home_abbr': 'detroit-mercy',
                'home_name': 'Detroit',
                'home_rank': None,
                'home_score': 69,
                'losing_abbr': 'detroit-mercy',
                'losing_name': 'Detroit',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'wright-state',
                'winning_name': 'Wright State'},
                {'away_abbr': 'stony-brook',
                'away_name': 'Stony Brook',
                'away_rank': None,
                'away_score': 73,
                'boxscore': '2020-01-05-13-maine',
                'home_abbr': 'maine',
                'home_name': 'Maine',
                'home_rank': None,
                'home_score': 52,
                'losing_abbr': 'maine',
                'losing_name': 'Maine',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'stony-brook',
                'winning_name': 'Stony Brook'},
                {'away_abbr': 'manhattan',
                'away_name': 'Manhattan',
                'away_rank': None,
                'away_score': 67,
                'boxscore': '2020-01-05-13-niagara',
                'home_abbr': 'niagara',
                'home_name': 'Niagara',
                'home_rank': None,
                'home_score': 62,
                'losing_abbr': 'niagara',
                'losing_name': 'Niagara',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'manhattan',
                'winning_name': 'Manhattan'},
                {'away_abbr': 'fairfield',
                'away_name': 'Fairfield',
                'away_rank': None,
                'away_score': 46,
                'boxscore': '2020-01-05-14-canisius',
                'home_abbr': 'canisius',
                'home_name': 'Canisius',
                'home_rank': None,
                'home_score': 42,
                'losing_abbr': 'canisius',
                'losing_name': 'Canisius',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'fairfield',
                'winning_name': 'Fairfield'},
                {'away_abbr': 'davidson',
                'away_name': 'Davidson',
                'away_rank': None,
                'away_score': 64,
                'boxscore': '2020-01-05-14-duquesne',
                'home_abbr': 'duquesne',
                'home_name': 'Duquesne',
                'home_rank': None,
                'home_score': 71,
                'losing_abbr': 'davidson',
                'losing_name': 'Davidson',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'duquesne',
                'winning_name': 'Duquesne'},
                {'away_abbr': 'la-salle',
                'away_name': 'La Salle',
                'away_rank': None,
                'away_score': 66,
                'boxscore': '2020-01-05-14-fordham',
                'home_abbr': 'fordham',
                'home_name': 'Fordham',
                'home_rank': None,
                'home_score': 60,
                'losing_abbr': 'fordham',
                'losing_name': 'Fordham',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'la-salle',
                'winning_name': 'La Salle'},
                {'away_abbr': 'iupui',
                'away_name': 'IUPUI',
                'away_rank': None,
                'away_score': 93,
                'boxscore': '2020-01-05-14-green-bay',
                'home_abbr': 'green-bay',
                'home_name': 'Green Bay',
                'home_rank': None,
                'home_score': 78,
                'losing_abbr': 'green-bay',
                'losing_name': 'Green Bay',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'iupui',
                'winning_name': 'IUPUI'},
                {'away_abbr': 'bucknell',
                'away_name': 'Bucknell',
                'away_rank': None,
                'away_score': 78,
                'boxscore': '2020-01-05-14-lafayette',
                'home_abbr': 'lafayette',
                'home_name': 'Lafayette',
                'home_rank': None,
                'home_score': 66,
                'losing_abbr': 'lafayette',
                'losing_name': 'Lafayette',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'bucknell',
                'winning_name': 'Bucknell'},
                {'away_abbr': 'loyola-md',
                'away_name': 'Loyola (MD)',
                'away_rank': None,
                'away_score': 71,
                'boxscore': '2020-01-05-14-lehigh',
                'home_abbr': 'lehigh',
                'home_name': 'Lehigh',
                'home_rank': None,
                'home_score': 78,
                'losing_abbr': 'loyola-md',
                'losing_name': 'Loyola (MD)',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'lehigh',
                'winning_name': 'Lehigh'},
                {'away_abbr': 'illinois-chicago',
                'away_name': 'UIC',
                'away_rank': None,
                'away_score': 62,
                'boxscore': '2020-01-05-14-milwaukee',
                'home_abbr': 'milwaukee',
                'home_name': 'Milwaukee',
                'home_rank': None,
                'home_score': 64,
                'losing_abbr': 'illinois-chicago',
                'losing_name': 'UIC',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'milwaukee',
                'winning_name': 'Milwaukee'},
                {'away_abbr': 'iona',
                'away_name': 'Iona',
                'away_rank': None,
                'away_score': 61,
                'boxscore': '2020-01-05-14-monmouth',
                'home_abbr': 'monmouth',
                'home_name': 'Monmouth',
                'home_rank': None,
                'home_score': 73,
                'losing_abbr': 'iona',
                'losing_name': 'Iona',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'monmouth',
                'winning_name': 'Monmouth'},
                {'away_abbr': 'siena',
                'away_name': 'Siena',
                'away_rank': None,
                'away_score': 77,
                'boxscore': '2020-01-05-14-rider',
                'home_abbr': 'rider',
                'home_name': 'Rider',
                'home_rank': None,
                'home_score': 85,
                'losing_abbr': 'siena',
                'losing_name': 'Siena',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'rider',
                'winning_name': 'Rider'},
                {'away_abbr': 'marist',
                'away_name': 'Marist',
                'away_rank': None,
                'away_score': 40,
                'boxscore': '2020-01-05-14-saint-peters',
                'home_abbr': 'saint-peters',
                'home_name': "St. Peter's",
                'home_rank': None,
                'home_score': 66,
                'losing_abbr': 'marist',
                'losing_name': 'Marist',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'saint-peters',
                'winning_name': "St. Peter's"},
                {'away_abbr': 'boston-university',
                'away_name': 'Boston University',
                'away_rank': None,
                'away_score': 63,
                'boxscore': '2020-01-05-15-american',
                'home_abbr': 'american',
                'home_name': 'American',
                'home_rank': None,
                'home_score': 67,
                'losing_abbr': 'boston-university',
                'losing_name': 'Boston University',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'american',
                'winning_name': 'American'},
                {'away_abbr': 'Northland',
                'away_name': 'Northland',
                'away_rank': None,
                'away_score': 43,
                'boxscore': '2020-01-05-15-north-dakota-state',
                'home_abbr': 'north-dakota-state',
                'home_name': 'North Dakota State',
                'home_rank': None,
                'home_score': 97,
                'losing_abbr': 'Northland',
                'losing_name': 'Northland',
                'non_di': True,
                'top_25': False,
                'winning_abbr': 'north-dakota-state',
                'winning_name': 'North Dakota State'},
                {'away_abbr': 'northern-kentucky',
                'away_name': 'Northern Kentucky',
                'away_rank': None,
                'away_score': 75,
                'boxscore': '2020-01-05-15-oakland',
                'home_abbr': 'oakland',
                'home_name': 'Oakland',
                'home_rank': None,
                'home_score': 64,
                'losing_abbr': 'oakland',
                'losing_name': 'Oakland',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'northern-kentucky',
                'winning_name': 'Northern Kentucky'},
                {'away_abbr': 'st-bonaventure',
                'away_name': 'St. Bonaventure',
                'away_rank': None,
                'away_score': 71,
                'boxscore': '2020-01-05-16-george-washington',
                'home_abbr': 'george-washington',
                'home_name': 'George Washington',
                'home_rank': None,
                'home_score': 66,
                'losing_abbr': 'george-washington',
                'losing_name': 'George Washington',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'st-bonaventure',
                'winning_name': 'St. Bonaventure'},
                {'away_abbr': 'massachusetts',
                'away_name': 'UMass',
                'away_rank': None,
                'away_score': 80,
                'boxscore': '2020-01-05-16-saint-louis',
                'home_abbr': 'saint-louis',
                'home_name': 'Saint Louis',
                'home_rank': None,
                'home_score': 83,
                'losing_abbr': 'massachusetts',
                'losing_name': 'UMass',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'saint-louis',
                'winning_name': 'Saint Louis'},
                {'away_abbr': 'denver',
                'away_name': 'Denver',
                'away_rank': None,
                'away_score': 78,
                'boxscore': '2020-01-05-16-south-dakota',
                'home_abbr': 'south-dakota',
                'home_name': 'South Dakota',
                'home_rank': None,
                'home_score': 80,
                'losing_abbr': 'denver',
                'losing_name': 'Denver',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'south-dakota',
                'winning_name': 'South Dakota'},
                {'away_abbr': 'st-johns-ny',
                'away_name': "St. John's (NY)",
                'away_rank': None,
                'away_score': 67,
                'boxscore': '2020-01-05-16-xavier',
                'home_abbr': 'xavier',
                'home_name': 'Xavier',
                'home_rank': None,
                'home_score': 75,
                'losing_abbr': 'st-johns-ny',
                'losing_name': "St. John's (NY)",
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'xavier',
                'winning_name': 'Xavier'},
                {'away_abbr': 'ipfw',
                'away_name': 'Purdue-Fort Wayne',
                'away_rank': None,
                'away_score': 69,
                'boxscore': '2020-01-05-17-north-dakota',
                'home_abbr': 'north-dakota',
                'home_name': 'North Dakota',
                'home_rank': None,
                'home_score': 83,
                'losing_abbr': 'ipfw',
                'losing_name': 'Purdue-Fort Wayne',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'north-dakota',
                'winning_name': 'North Dakota'},
                {'away_abbr': 'houston-baptist',
                'away_name': 'Houston Christian',
                'away_rank': None,
                'away_score': 79,
                'boxscore': '2020-01-05-17-northwestern-state',
                'home_abbr': 'northwestern-state',
                'home_name': 'Northwestern State',
                'home_rank': None,
                'home_score': 106,
                'losing_abbr': 'houston-baptist',
                'losing_name': 'Houston Christian',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'northwestern-state',
                'winning_name': 'Northwestern State'},
                {'away_abbr': 'oregon-state',
                'away_name': 'Oregon State',
                'away_rank': None,
                'away_score': 76,
                'boxscore': '2020-01-05-18-colorado',
                'home_abbr': 'colorado',
                'home_name': 'Colorado',
                'home_rank': None,
                'home_score': 68,
                'losing_abbr': 'colorado',
                'losing_name': 'Colorado',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'oregon-state',
                'winning_name': 'Oregon State'},
                {'away_abbr': 'northwestern',
                'away_name': 'Northwestern',
                'away_rank': None,
                'away_score': 68,
                'boxscore': '2020-01-05-19-minnesota',
                'home_abbr': 'minnesota',
                'home_name': 'Minnesota',
                'home_rank': None,
                'home_score': 77,
                'losing_abbr': 'northwestern',
                'losing_name': 'Northwestern',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'minnesota',
                'winning_name': 'Minnesota'},
                {'away_abbr': 'purdue',
                'away_name': 'Purdue',
                'away_rank': None,
                'away_score': 37,
                'boxscore': '2020-01-05-20-illinois',
                'home_abbr': 'illinois',
                'home_name': 'Illinois',
                'home_rank': None,
                'home_score': 63,
                'losing_abbr': 'purdue',
                'losing_name': 'Purdue',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'illinois',
                'winning_name': 'Illinois'},
                {'away_abbr': 'southern-california',
                'away_name': 'USC',
                'away_rank': None,
                'away_score': 40,
                'boxscore': '2020-01-05-22-washington',
                'home_abbr': 'washington',
                'home_name': 'Washington',
                'home_rank': None,
                'home_score': 72,
                'losing_abbr': 'southern-california',
                'losing_name': 'USC',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'washington',
                'winning_name': 'Washington'}],
            '1-6-2020': [
                {'away_abbr': 'west-virginia',
                'away_name': 'West Virginia',
                'away_rank': 17,
                'away_score': 55,
                'boxscore': '2020-01-06-21-oklahoma-state',
                'home_abbr': 'oklahoma-state',
                'home_name': 'Oklahoma State',
                'home_rank': None,
                'home_score': 41,
                'losing_abbr': 'oklahoma-state',
                'losing_name': 'Oklahoma State',
                'non_di': False,
                'top_25': True,
                'winning_abbr': 'west-virginia',
                'winning_name': 'West Virginia'},
                {'away_abbr': 'louisiana-lafayette',
                'away_name': 'Louisiana',
                'away_rank': None,
                'away_score': 81,
                'boxscore': '2020-01-06-19-appalachian-state',
                'home_abbr': 'appalachian-state',
                'home_name': 'Appalachian State',
                'home_rank': None,
                'home_score': 73,
                'losing_abbr': 'appalachian-state',
                'losing_name': 'Appalachian State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'louisiana-lafayette',
                'winning_name': 'Louisiana'},
                {'away_abbr': 'georgia-southern',
                'away_name': 'Georgia Southern',
                'away_rank': None,
                'away_score': 73,
                'boxscore': '2020-01-06-19-arkansas-little-rock',
                'home_abbr': 'arkansas-little-rock',
                'home_name': 'Little Rock',
                'home_rank': None,
                'home_score': 79,
                'losing_abbr': 'georgia-southern',
                'losing_name': 'Georgia Southern',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'arkansas-little-rock',
                'winning_name': 'Little Rock'},
                {'away_abbr': 'colgate',
                'away_name': 'Colgate',
                'away_rank': None,
                'away_score': 70,
                'boxscore': '2020-01-06-19-army',
                'home_abbr': 'army',
                'home_name': 'Army',
                'home_rank': None,
                'home_score': 65,
                'losing_abbr': 'army',
                'losing_name': 'Army',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'colgate',
                'winning_name': 'Colgate'},
                {'away_abbr': 'louisiana-monroe',
                'away_name': 'Louisiana-Monroe',
                'away_rank': None,
                'away_score': 64,
                'boxscore': '2020-01-06-19-coastal-carolina',
                'home_abbr': 'coastal-carolina',
                'home_name': 'Coastal Carolina',
                'home_rank': None,
                'home_score': 93,
                'losing_abbr': 'louisiana-monroe',
                'losing_name': 'Louisiana-Monroe',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'coastal-carolina',
                'winning_name': 'Coastal Carolina'},
                {'away_abbr': 'norfolk-state',
                'away_name': 'Norfolk State',
                'away_rank': None,
                'away_score': 82,
                'boxscore': '2020-01-06-19-coppin-state',
                'home_abbr': 'coppin-state',
                'home_name': 'Coppin State',
                'home_rank': None,
                'home_score': 59,
                'losing_abbr': 'coppin-state',
                'losing_name': 'Coppin State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'norfolk-state',
                'winning_name': 'Norfolk State'},
                {'away_abbr': 'bethune-cookman',
                'away_name': 'Bethune-Cookman',
                'away_rank': None,
                'away_score': 102,
                'boxscore': '2020-01-06-19-howard',
                'home_abbr': 'howard',
                'home_name': 'Howard',
                'home_rank': None,
                'home_score': 73,
                'losing_abbr': 'howard',
                'losing_name': 'Howard',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'bethune-cookman',
                'winning_name': 'Bethune-Cookman'},
                {'away_abbr': 'south-carolina-state',
                'away_name': 'South Carolina State',
                'away_rank': None,
                'away_score': 63,
                'boxscore': '2020-01-06-19-morgan-state',
                'home_abbr': 'morgan-state',
                'home_name': 'Morgan State',
                'home_rank': None,
                'home_score': 77,
                'losing_abbr': 'south-carolina-state',
                'losing_name': 'South Carolina State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'morgan-state',
                'winning_name': 'Morgan State'},
                {'away_abbr': 'florida-am',
                'away_name': 'Florida A&M',
                'away_rank': None,
                'away_score': 90,
                'boxscore': '2020-01-06-19-north-carolina-at',
                'home_abbr': 'north-carolina-at',
                'home_name': 'North Carolina A&T',
                'home_rank': None,
                'home_score': 97,
                'losing_abbr': 'florida-am',
                'losing_name': 'Florida A&M',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'north-carolina-at',
                'winning_name': 'North Carolina A&T'},
                {'away_abbr': 'georgia-state',
                'away_name': 'Georgia State',
                'away_rank': None,
                'away_score': 87,
                'boxscore': '2020-01-06-20-arkansas-state',
                'home_abbr': 'arkansas-state',
                'home_name': 'Arkansas State',
                'home_rank': None,
                'home_score': 90,
                'losing_abbr': 'georgia-state',
                'losing_name': 'Georgia State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'arkansas-state',
                'winning_name': 'Arkansas State'},
                {'away_abbr': 'alabama-state',
                'away_name': 'Alabama State',
                'away_rank': None,
                'away_score': 63,
                'boxscore': '2020-01-06-20-grambling',
                'home_abbr': 'grambling',
                'home_name': 'Grambling',
                'home_rank': None,
                'home_score': 68,
                'losing_abbr': 'alabama-state',
                'losing_name': 'Alabama State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'grambling',
                'winning_name': 'Grambling'},
                {'away_abbr': 'alabama-am',
                'away_name': 'Alabama A&M',
                'away_rank': None,
                'away_score': 66,
                'boxscore': '2020-01-06-20-jackson-state',
                'home_abbr': 'jackson-state',
                'home_name': 'Jackson State',
                'home_rank': None,
                'home_score': 57,
                'losing_abbr': 'jackson-state',
                'losing_name': 'Jackson State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'alabama-am',
                'winning_name': 'Alabama A&M'},
                {'away_abbr': 'south-alabama',
                'away_name': 'South Alabama',
                'away_rank': None,
                'away_score': 66,
                'boxscore': '2020-01-06-20-texas-arlington',
                'home_abbr': 'texas-arlington',
                'home_name': 'UT Arlington',
                'home_rank': None,
                'home_score': 54,
                'losing_abbr': 'texas-arlington',
                'losing_name': 'UT Arlington',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'south-alabama',
                'winning_name': 'South Alabama'},
                {'away_abbr': 'alcorn-state',
                'away_name': 'Alcorn State',
                'away_rank': None,
                'away_score': 95,
                'boxscore': '2020-01-06-20-texas-southern',
                'home_abbr': 'texas-southern',
                'home_name': 'Texas Southern',
                'home_rank': None,
                'home_score': 80,
                'losing_abbr': 'texas-southern',
                'losing_name': 'Texas Southern',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'alcorn-state',
                'winning_name': 'Alcorn State'},
                {'away_abbr': 'troy',
                'away_name': 'Troy',
                'away_rank': None,
                'away_score': 71,
                'boxscore': '2020-01-06-20-texas-state',
                'home_abbr': 'texas-state',
                'home_name': 'Texas State',
                'home_rank': None,
                'home_score': 63,
                'losing_abbr': 'texas-state',
                'losing_name': 'Texas State',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'troy',
                'winning_name': 'Troy'},
                {'away_abbr': 'southern',
                'away_name': 'Southern',
                'away_rank': None,
                'away_score': 54,
                'boxscore': '2020-01-06-21-prairie-view',
                'home_abbr': 'prairie-view',
                'home_name': 'Prairie View',
                'home_rank': None,
                'home_score': 64,
                'losing_abbr': 'southern',
                'losing_name': 'Southern',
                'non_di': False,
                'top_25': False,
                'winning_abbr': 'prairie-view',
                'winning_name': 'Prairie View'}
            ]
        }

        result = Boxscores(datetime(2020, 1, 5), datetime(2020, 1, 6)).games

        assert result == expected

    @mock.patch('sportsipy.utils._rate_limit_pq', side_effect=mock_pyquery)
    def test_boxscores_search_string_representation(self, *args, **kwargs):
        result = Boxscores(datetime(2020, 1, 5))

        assert result.__repr__() == 'NCAAB games for 1-5-2020'
